/**
 * Question Desk server code: every word staff and the stage read, in each app language.
 * Apps Script runs every server file as one program; see Code.js for settings and routing.
 *
 * Two catalogs, split by who is reading, because they ship differently:
 *   UI_TEXT (text.js)  the audience. Every language goes to the page; the phone picks, because
 *                      there is no reader to ask.
 *   APP_TEXT (here)    staff, and the people on stage. The server knows who is reading, so it
 *                      resolves one language and sends only that, as BOOT.words.
 *
 * Keys are flat and dotted, and name a place, not a phrase: two screens that happen to say the
 * same English word still get their own key, because one Spanish word rarely fits both.
 * Languages are CONFIG.appLanguages, which is deliberately not CONFIG.languages — those names
 * are compared as values (participants.js, summaries.js) and must not grow entries.
 */

// ---------------------------------------------------------------- staff-facing text

const APP_TEXT = {
  'shared.dialog.ok': { en: 'OK' },
  'shared.dialog.typePrompt': { en: 'To confirm, type ' },
  'shared.failed': { en: 'Something went wrong.' },

  'home.staff.heading': { en: 'For staff' },
  'home.staff.none': { en: 'No open sessions assigned to you.' },
  'home.staff.admin': { en: 'Open the admin page' },
  'home.staff.signIn': { en: 'QA Facilitators and administrators: {link} with your {domain} account.' },
  'home.staff.signInLink': { en: 'sign in' },
  'home.session.active': { en: 'Active' },
  'home.session.inactive': { en: 'Not active' },
  'home.link.present': { en: 'Room screen' },
  'home.link.queue': { en: 'Queue' },

  'mod.title': { en: 'Question queue' },
  'mod.pageTitle': { en: 'QA - {name}' },
  'mod.pageTitleRoom': { en: 'QA - {name} ({room})' },
  'mod.switchSession': { en: 'Switch session' },
  'mod.optionEnded': { en: ' (ended)' },
  'mod.optionInactive': { en: ' (not active)' },
  'mod.loading': { en: 'Loading…' },
  'mod.roomScreen': { en: 'Room screen' },
  'mod.panelLink': { en: 'Panelist view' },
  'mod.panelLinkTitle': { en: 'The question being answered, large, for the panel table' },
  'mod.shortcuts': { en: 'Shortcuts' },
  'mod.shortcutsTitle': { en: 'Keyboard shortcuts (press ?)' },
  'mod.admin': { en: 'Admin' },
  'mod.endedNotice': { en: 'This session has ended. The queue is read-only.' },
  'mod.selectedRegion': { en: 'Selected questions' },
  'mod.selGroup': { en: 'Group as…' },
  'mod.selUngroup': { en: 'Ungroup' },
  'mod.selAnswered': { en: 'Answered' },
  'mod.selDismiss': { en: 'Dismiss' },
  'mod.selClear': { en: 'Clear' },
  'mod.selCount.one': { en: '{n} question selected' },
  'mod.selCount.other': { en: '{n} questions selected' },
  'mod.toggleTitle': { en: 'Click to pause or resume new questions' },
  'mod.accepting': { en: 'Accepting questions' },
  'mod.paused': { en: 'Paused — not accepting questions' },
  'mod.groupNow': { en: 'Group now' },
  'mod.groupNowTitle': { en: 'Group and translate waiting questions now, even when automatic grouping is off' },
  'mod.grouping': { en: 'Grouping…' },
  'mod.groupingFailed': { en: 'Grouping failed — retry' },
  'mod.autoGroup': { en: 'Group automatically' },
  'mod.autoGroupTitle': { en: 'Every minute, Gemini groups new questions into topics. Off: questions are still translated, and you group them yourself.' },
  'mod.autoShow': { en: 'Show on phones when answering' },
  'mod.autoShowTitle': { en: 'Answer now also shows the topic on participants\' phones' },
  'mod.roomQuestions': { en: 'List on the room screen' },
  'mod.roomQuestionsTitle': { en: 'The room screen lists what\'s on participants\' phones, most Me too first' },
  'mod.originals': { en: 'Show original wording' },
  'mod.prepared': { en: 'Prepared questions' },
  'mod.dismissedBox': { en: 'Dismissed' },
  'mod.empty': { en: 'Waiting for the first question.' },
  'mod.groupDialogTitle': { en: 'Group questions' },
  'mod.groupHint': { en: 'Type a new topic, or pick one that exists to add these questions to it.' },
  'mod.topicName': { en: 'Topic name' },
  'mod.groupOk': { en: 'Group' },
  'mod.cancel': { en: 'Cancel' },
  'mod.pillActive': { en: 'Active' },
  'mod.pillEnded': { en: 'Ended' },
  'mod.pillInactive': { en: 'Not active' },
  'mod.tally': { en: '{questions} across {topics}' },
  'mod.tallyQuestions.one': { en: '{n} question' },
  'mod.tallyQuestions.other': { en: '{n} questions' },
  'mod.tallyTopics.one': { en: '{n} topic' },
  'mod.tallyTopics.other': { en: '{n} topics' },
  'mod.saveFailed': { en: 'That change didn\'t save{detail} — reloaded the queue' },
  'mod.groupingDown': { en: 'Automatic grouping isn\'t working right now, so new questions aren\'t grouped or translated. Until it recovers, they\'re sorted below by a word they share. ({detail})' },
  'mod.looseMentions': { en: 'Not yet grouped · mentions “{word}”' },
  'mod.looseOther': { en: 'Not yet grouped · other questions' },
  'mod.notYetGrouped': { en: 'Not yet grouped' },
  'mod.questionsGroup': { en: 'Questions' },
  'mod.logistics': { en: 'About running the event: it is with the Event Coordinators as well as you.' },
  'mod.logisticsSorted': { en: 'About running the event. The Event Coordinators have sorted it.' },
  'mod.addToQueue': { en: 'Add to queue' },
  'mod.restore': { en: 'Restore' },
  'mod.readOut': { en: 'Read out' },
  'mod.save': { en: 'Save' },
  'mod.edit': { en: 'Edit' },
  'mod.remove': { en: 'Remove' },
  'mod.writeItYourself': { en: 'Write it yourself' },
  'mod.mergeBadAnswer': { en: 'Gemini\'s answer couldn\'t be used. Try again.' },
  'mod.mergeUnreachable': { en: 'Couldn\'t reach Question Desk ({detail}). Try again.' },
  'mod.connectionProblem': { en: 'connection problem' },
  'mod.mergeFailed': { en: 'Couldn\'t write it: {why}' },
  'mod.translations': { en: 'Translations · {names}' },
  'mod.topicCount.one': { en: '{n} question' },
  'mod.topicCount.other': { en: '{n} questions' },
  'mod.topicCountDone.one': { en: '{n} question · all answered' },
  'mod.topicCountDone.other': { en: '{n} questions · all answered' },
  'mod.meToo': { en: ' · +{n} me too' },
  'mod.answeringNow': { en: 'Answering now' },
  'mod.answeringNowTimer': { en: 'Answering now · {time}' },
  'mod.answerNow': { en: 'Answer now' },
  'mod.stopAnswering': { en: 'Stop answering' },
  'mod.answerNowTitle': { en: 'Put this topic on the room screen and participants\' phones as the one being answered' },
  'mod.stopAnsweringTitle': { en: 'Take this topic off the room screen and participants\' phones' },
  'mod.answerNowQuestionTitle': { en: 'Show this question on the room screen and phones as the one being answered' },
  'mod.onPhones': { en: 'On phones ✓' },
  'mod.showOnPhones': { en: 'Show on phones' },
  'mod.onPhonesTitle': { en: 'Participants can see this topic and tap Me too. Click to hide it from phones.' },
  'mod.showOnPhonesTitle': { en: 'Let participants see this topic label and tap Me too' },
  'mod.phonesOn': { en: 'Phones ✓' },
  'mod.phones': { en: 'Phones' },
  'mod.phonesOnTitle': { en: 'Participants can see this question and tap Me too. Click to hide it from phones.' },
  'mod.phonesTitle': { en: 'Let participants see this question (translated into their language) and tap Me too' },
  'mod.dismissAll.one': { en: 'Dismiss all {n} question' },
  'mod.dismissAll.other': { en: 'Dismiss all {n} questions' },
  'mod.dismissTopicTitle': { en: 'Dismiss this topic?' },
  'mod.dismissTopicBody.one': { en: 'All {n} question under "{topic}" move to Dismissed at the bottom of the page and come off participants\' phones. You can restore them.' },
  'mod.dismissTopicBody.other': { en: 'All {n} questions under "{topic}" move to Dismissed at the bottom of the page and come off participants\' phones. You can restore them.' },
  'mod.dismissAllOk': { en: 'Dismiss all' },
  'mod.answeredTag': { en: '✓ Answered' },
  'mod.answered': { en: 'Answered' },
  'mod.reopen': { en: 'Reopen' },
  'mod.answeredTitle': { en: 'Mark this question as answered' },
  'mod.reopenTitle': { en: 'Mark as not answered yet' },
  'mod.dismiss': { en: 'Dismiss' },
  'mod.dismissTitle': { en: 'Move to Dismissed at the bottom of the page' },
  'mod.lostConnection': { en: 'Lost connection — retrying' },
  'mod.notUpdating': { en: 'Not updating — check the connection' },
  'mod.updated': { en: 'Updated {at}' },
  'mod.keysTitle': { en: 'Keyboard shortcuts' },
  'mod.keysOk': { en: 'Got it' },
  'mod.keys.next': { en: 'Next question' },
  'mod.keys.nextPress': { en: 'J or ↓' },
  'mod.keys.prev': { en: 'Previous question' },
  'mod.keys.prevPress': { en: 'K or ↑' },
  'mod.keys.tick': { en: 'Tick the question (then Group as…, Ungroup, Answered or Dismiss)' },
  'mod.keys.answered': { en: 'Answered (or Reopen)' },
  'mod.keys.dismiss': { en: 'Dismiss' },
  'mod.keys.live': { en: 'Answer now / Stop answering for its topic' },
  'mod.keys.phones': { en: 'Show on or hide from phones (a question not in a topic, or else its topic)' },
  'mod.keys.merge': { en: 'Write (or rewrite) one question to read out for the topic' },
  'mod.keys.group': { en: 'Group now' },
  'mod.keys.originals': { en: 'Show original wording' },
  'mod.keys.clear': { en: 'Clear the selection' },
  'mod.keys.list': { en: 'This list' },

  'admin.top.questionDeskAdministration': { en: 'Question Desk Administration' },
  'admin.top.sessions': { en: 'Sessions' },
  'admin.top.people': { en: 'People' },
  'admin.top.branding': { en: 'Branding' },
  'admin.top.activity': { en: 'Activity' },
  'admin.top.healthTesting': { en: 'Health & testing' },
  'admin.sessions.newEvent': { en: 'New event' },
  'admin.sessions.newSession': { en: 'New session' },
  'admin.sessions.exportCsv': { en: 'Export CSV' },
  'admin.sessions.importCsv': { en: 'Import CSV' },
  'admin.sessions.sessionsCsv': { en: 'Sessions CSV' },
  'admin.sessions.exportCopy': { en: 'Copy' },
  'admin.sessions.exportClose': { en: 'Close' },
  'admin.sessions.checklistTitle': { en: 'Day-of checklist' },
  'admin.sessions.checklistRefresh': { en: 'Check again' },
  'admin.sessions.checklistClose': { en: 'Close' },
  'admin.sessions.importSessionsFromCsv': { en: 'Import sessions from CSV' },
  'admin.sessions.whenASessionAlready': { en: 'When a session already exists (same name, start and end — or same name when it has no times)' },
  'admin.sessions.importCheck': { en: 'Check file' },
  'admin.sessions.importGo': { en: 'Import' },
  'admin.sessions.importCancel': { en: 'Cancel' },
  'admin.sessions.eventFormTitle': { en: 'New event' },
  'admin.sessions.evname.hint': { en: 'Spring Family Conference 2027' },
  'admin.sessions.groupsTheSessionsHeld': { en: 'Groups the sessions held at one event, such as a conference with several rooms.' },
  'admin.sessions.qaFacilitatorsForEvery': { en: 'QA Facilitators for every session in this event' },
  'admin.sessions.theyCanRunThe': { en: 'They can run the queue for all of this event\'s sessions. Sessions can add more of their own. (Summaries go to the Session Summary Email Recipients on the People tab.)' },
  'admin.sessions.eventCoordinators': { en: 'Event Coordinators' },
  'admin.sessions.theyGetThisEvent': { en: 'They get this event\'s own portal: every question the audience asks about running it — rooms, timing, access, food — from all its sessions. Add people to the role on the People tab first.' },
  'admin.sessions.languages': { en: 'Languages' },
  'admin.sessions.eventBrandingOptional': { en: 'Event branding (optional)' },
  'admin.sessions.overridesTheSiteBranding': { en: 'Overrides the site branding for this event\'s sessions. Leave a field blank to use the site\'s. A session can still set its own name, color and logo.' },
  'admin.sessions.accentColor': { en: 'Accent color' },
  'admin.sessions.evaccent.says': { en: 'Event accent color' },
  'admin.sessions.roomScreenBackgroundDark': { en: 'Room screen background — dark' },
  'admin.sessions.evdark.says': { en: 'Event dark background' },
  'admin.sessions.roomScreenBackgroundLight': { en: 'Room screen background — light' },
  'admin.sessions.evlight.says': { en: 'Event light background' },
  'admin.sessions.logo': { en: 'Logo' },
  'admin.sessions.evlogoremove': { en: 'Remove event logo' },
  'admin.sessions.evlogolater': { en: 'Save the event first, then edit it to add a logo.' },
  'admin.sessions.saveEvent': { en: 'Save event' },
  'admin.sessions.cancelEvent': { en: 'Cancel' },
  'admin.sessions.formTitle': { en: 'New session' },
  'admin.sessions.forAdministratorsAndQa': { en: 'For administrators and QA Facilitators, e.g. "Family night — Sept".' },
  'admin.sessions.froom.hint': { en: 'Ballroom A' },
  'admin.sessions.whereItHappensShown': { en: 'Where it happens. Shown to staff and in their emails; participants never see it.' },
  'admin.sessions.howPeopleJoin': { en: 'How people join' },
  'admin.sessions.roomScreenTheme': { en: 'Room screen theme' },
  'admin.sessions.useTheGuestPage': { en: 'Use the guest page for' },
  'admin.sessions.avoidsGoogleSSorry': { en: 'Avoids Google\'s "Sorry, unable to open the file" on phones and browsers signed into several Google accounts. Unticked opens Google\'s address directly.' },
  'admin.sessions.guestPageAddressFor': { en: 'Guest page address for this session (optional)' },
  'admin.sessions.fguesturl.hint': { en: 'Uses the address on the Branding tab' },
  'admin.sessions.leaveBlankToUse': { en: 'Leave blank to use the organization\'s guest page. Fill in to use another site, such as a partner\'s. A shareable questions link uses the guest page when Room screen or PowerPoint slide is ticked.' },
  'admin.sessions.fprepared.hint': { en: 'One question per line' },
  'admin.sessions.loadedAheadOfTime': { en: 'Loaded ahead of time and kept out of sight. A QA Facilitator adds each one to the queue when it\'s useful. Saving replaces the ones not yet added.' },
  'admin.sessions.scheduleOptional': { en: 'Schedule (optional)' },
  'admin.sessions.checkedEveryMinuteEnding': { en: 'Checked every minute. Ending sends the summary if the box above is ticked. You can still start, stop and end by hand.' },
  'admin.sessions.sessionBrandingOptional': { en: 'Session branding (optional)' },
  'admin.sessions.forPartnerEventsLeave': { en: 'For partner events. Leave blank to use your organization\'s branding.' },
  'admin.sessions.accentColor2': { en: 'Accent color' },
  'admin.sessions.faccent.says': { en: 'Session accent color' },
  'admin.sessions.logo2': { en: 'Logo' },
  'admin.sessions.flogoremove': { en: 'Remove session logo' },
  'admin.sessions.flogolater': { en: 'Save the session first, then edit it to add a logo.' },
  'admin.sessions.qaFacilitatorsForThis': { en: 'QA Facilitators for this session' },
  'admin.sessions.administratorsCanRunEvery': { en: 'Administrators can run every session. Add people to the QA Facilitator list on the People tab.' },
  'admin.sessions.saveSession': { en: 'Save session' },
  'admin.sessions.cancelSession': { en: 'Cancel' },
  'admin.people.administrators': { en: 'Administrators' },
  'admin.people.canCreateAndRun': { en: 'Can create and run sessions, manage people, and change branding.' },
  'admin.people.nameDomainOrg': { en: 'name@domain.org' },
  'admin.people.administratorEmail': { en: 'Administrator email' },
  'admin.people.add': { en: 'Add' },
  'admin.people.qaFacilitators': { en: 'QA Facilitators' },
  'admin.people.runTheQueueFor': { en: 'Run the queue for the sessions they are assigned to: group, merge, approve topics for phones, and mark questions answered.' },
  'admin.people.nameDomainOrg2': { en: 'name@domain.org' },
  'admin.people.qaFacilitatorEmail': { en: 'QA Facilitator email' },
  'admin.people.add2': { en: 'Add' },
  'admin.people.eventCoordinators': { en: 'Event Coordinators' },
  'admin.people.seeTheQuestionsAbout': { en: 'See the questions about running an event — rooms, timing, access, food — in their own portal, for the events they are assigned to.' },
  'admin.people.nameDomainOrg3': { en: 'name@domain.org' },
  'admin.people.eventCoordinatorEmail': { en: 'Event Coordinator email' },
  'admin.people.add3': { en: 'Add' },
  'admin.people.sessionSummaryEmailRecipients': { en: 'Session Summary Email Recipients' },
  'admin.people.summaryHint': { en: 'Get every session\'s questions summary when it ends. Anyone can be added, even outside your organization.' },
  'admin.people.nameDomainOrg4': { en: 'name@domain.org' },
  'admin.people.sessionSummaryEmailRecipient': { en: 'Session summary email recipient' },
  'admin.people.add4': { en: 'Add' },
  'admin.branding.languages': { en: 'Languages' },
  'admin.branding.saveLangs': { en: 'Save languages' },
  'admin.branding.branding': { en: 'Branding' },
  'admin.branding.shownBesideTheLogo': { en: 'Shown beside the logo and as the sender name on emails.' },
  'admin.branding.accentColor': { en: 'Accent color' },
  'admin.branding.baccentpick.says': { en: 'Pick accent color' },
  'admin.branding.baccent.says': { en: 'Accent color hex' },
  'admin.branding.usedForButtonsOn': { en: 'Used for buttons on the participant page.' },
  'admin.branding.oneLineOnThe': { en: 'One line on the landing page and participant page, e.g. "Thank you for joining us tonight."' },
  'admin.branding.websiteOrContactLine': { en: 'Website or contact line on every page and email.' },
  'admin.branding.roomScreenBackgroundDark': { en: 'Room screen background — dark' },
  'admin.branding.bbgdark.says': { en: 'Dark background' },
  'admin.branding.roomScreenBackgroundLight': { en: 'Room screen background — light' },
  'admin.branding.bbglight.says': { en: 'Light background' },
  'admin.branding.bfavicon.hint': { en: 'https://your-site.org/icon.png' },
  'admin.branding.aLinkToA': { en: 'A link to a square PNG on your website. Google only accepts a public image link here, not an upload.' },
  'admin.branding.bguest.hint': { en: 'https://djsincla.github.io/question-desk/join/' },
  'admin.branding.advanced': { en: 'Advanced' },
  'admin.branding.saveBranding': { en: 'Save branding' },
  'admin.branding.logo': { en: 'Logo' },
  'admin.branding.removeLogo': { en: 'Remove logo' },
  'admin.branding.resizedInYourBrowser': { en: 'Resized in your browser before upload so pages stay fast on venue wifi. A wide logo on a transparent or white background works best.' },
  'admin.activity.activityLog': { en: 'Activity log' },
  'admin.activity.actSearch.hint': { en: 'Search people, actions, sessions…' },
  'admin.activity.actSearch.says': { en: 'Search the activity log' },
  'admin.activity.actTarget.says': { en: 'Show one session or event' },
  'admin.activity.actRefresh': { en: 'Refresh' },
  'admin.health.healthCheck': { en: 'Health check' },
  'admin.health.testsTheGeminiKey': { en: 'Tests the Gemini key and model, the every-minute trigger, the sheet, email quota and the app address. Admins are also emailed automatically if grouping fails 3 minutes in a row.' },
  'admin.health.runHealth': { en: 'Run health check' },
  'admin.health.sgrouping': { en: 'Last grouping' },
  'admin.health.squota': { en: 'Emails left today' },
  'admin.health.ssheet': { en: 'Submissions sheet' },
  'admin.health.dataAndReports': { en: 'Data and reports' },
  'admin.health.keepIt': { en: 'Keep it' },
  'admin.health.removeIt3Months': { en: 'Remove it 3 months after a session ends' },
  'admin.health.removeIt6Months': { en: 'Remove it 6 months after a session ends' },
  'admin.health.removeIt12Months': { en: 'Remove it 12 months after a session ends' },
  'admin.health.removeIt24Months': { en: 'Remove it 24 months after a session ends' },
  'admin.health.removingReplacesEachQuestion': { en: 'Removing replaces each question\'s original wording, its translation and merged questions with a note. Topics, languages, answered status, times and counts stay, so summaries and reports still add up. It can\'t be undone.' },
  'admin.health.settingsStorage': { en: 'Settings storage' },
  'admin.health.opssave': { en: 'Save' },
  'admin.health.opsreport': { en: 'Send me the weekly report now' },
  'admin.health.loadTest': { en: 'Load test' },
  'admin.health.simulatesAFullRoom': { en: 'Simulates a full room submitting at once, through the same code path phones use, against a throwaway session. Run it before an event, not during one.' },
  'admin.health.startLoad': { en: 'Start load test' },
  'admin.health.copyLoad': { en: 'Copy command' },
  'admin.health.stopLoad': { en: 'Finish and delete test data' },
  'admin.health.prompts': { en: 'Prompts' },
  'admin.health.exactlyWhatQuestionDesk': { en: 'Exactly what Question Desk asks Gemini, for each thing it does. Edit it to suit your audience; changes apply to the very next request. The rules underneath each prompt are always added and can\'t be edited — they are what keeps a question from being treated as an instruction, keeps topic labels in one language so questions group across languages, and keeps criticism unsoftened.' },
  'admin.health.promptsave': { en: 'Save prompt' },
  'admin.health.promptreset': { en: 'Reset to the built-in one' },
  'admin.health.alwaysAddedWhateverYou': { en: 'Always added, whatever you write' },
  'admin.health.gemini': { en: 'Gemini' },
  'admin.health.howQuestionDeskAsks': { en: 'How Question Desk asks Gemini to group, merge and translate. Saved changes apply to the very next request — no redeploy. More thinking can group and translate messy or mixed-language questions better, but takes longer; less thinking answers faster.' },
  'admin.health.gemkey.hint': { en: 'Paste a new key to replace it' },
  'admin.health.gemkeysave': { en: 'Save key' },
  'admin.health.gemkeyclear': { en: 'Remove key' },
  'admin.health.everyMinuteInThe': { en: 'Every minute, in the background. Quality matters most here.' },
  'admin.health.mergeIntoOneQuestion': { en: '"Merge into one question": a facilitator is waiting.' },
  'admin.health.showOnPhonesAnswer': { en: 'Show on phones, Answer now on one question, prepared questions.' },
  'admin.health.01LowerKeeps': { en: '0–1. Lower keeps topics and translations consistent and literal; 0–0.3 suits Question Desk.' },
  'admin.health.5100SmallerAnswers': { en: '5–100. Smaller answers sooner; larger groups a busy room in fewer requests.' },
  'admin.health.gemsave': { en: 'Save' },
  'admin.health.gemtest': { en: 'Try these settings' },
  'admin.health.gemreset': { en: 'Reset to defaults' },
  'admin.health.emailTitle': { en: 'Email links' },
  'admin.health.eto.hint': { en: 'one@example.org, two@example.org' },
  'admin.health.separateAddressesWithCommas': { en: 'Separate addresses with commas or new lines. Each person gets their own email.' },
  'admin.health.include': { en: 'Include' },
  'admin.health.esend': { en: 'Send' },
  'admin.health.ecancel': { en: 'Cancel' },
  'admin.health.dialogOk': { en: 'OK' },
  'admin.health.dialogCancel': { en: 'Cancel' },

  'admin.somethingWentWrong': { en: 'Something went wrong.' },
  'admin.selectedPressCtrlCmd': { en: 'Selected — press Ctrl/Cmd+C to copy' },
  'admin.allSessionsAndEvents': { en: 'All sessions and events' },
  'admin.loading': { en: 'Loading…' },
  'admin.sessionOrEvent': { en: 'Session or event' },
  'admin.nothingMatches': { en: 'Nothing matches.' },
  'admin.noWaitBetweenQuestions': { en: 'no wait between questions' },
  'admin.notActive': { en: 'Not active' },
  'admin.expandAllEvents': { en: 'Expand all events' },
  'admin.collapseAllEvents': { en: 'Collapse all events' },
  'admin.noEventsOrSessions': { en: 'No events or sessions yet. Create an event for a conference or meeting, then add its sessions.' },
  'admin.dragOrUseTo': { en: 'Drag ⋮⋮ or use ▲ ▼ to change the order of sessions within an event.' },
  'admin.notInAnEvent': { en: 'Not in an event' },
  'admin.usesTheSiteBranding': { en: 'Uses the site branding. Edit a session to put it in an event.' },
  'admin.moveEventUp': { en: 'Move event up' },
  'admin.moveEventDown': { en: 'Move event down' },
  'admin.showOrHideThis': { en: 'Show or hide this event\'s sessions' },
  'admin.ownBranding': { en: 'own branding' },
  'admin.siteBranding': { en: 'site branding' },
  'admin.addSession': { en: 'Add session' },
  'admin.editEvent': { en: 'Edit event' },
  'admin.emailQaFacilitators': { en: 'Email QA Facilitators' },
  'admin.noQaFacilitatorsAssigned': { en: 'No QA Facilitators assigned to this event or its sessions' },
  'admin.emailQaFacilitatorsTheir': { en: 'Email QA Facilitators their links?' },
  'admin.more': { en: 'More ▾' },
  'admin.dayOfChecklist': { en: 'Day-of checklist' },
  'admin.eventCoordinatorPortal': { en: 'Event Coordinator portal' },
  'admin.printQrSheets': { en: 'Print QR sheets' },
  'admin.aPrintablePageWith': { en: 'A printable page with the QR code for each shareable-link session' },
  'admin.emailSummaryForThe': { en: 'Email summary for the whole event' },
  'admin.duplicateEvent': { en: 'Duplicate event' },
  'admin.deleteEvent': { en: 'Delete event' },
  'admin.deleteThisEvent': { en: 'Delete this event?' },
  'admin.itsBrandingAndLogo': { en: 'Its branding and logo are deleted.' },
  'admin.eventDeleted': { en: 'Event deleted' },
  'admin.noSessionsYetUse': { en: 'No sessions yet. Use Add session.' },
  'admin.orderSaved': { en: 'Order saved' },
  'admin.dragToReorder': { en: 'Drag to reorder' },
  'admin.loadTest': { en: 'Load test' },
  'admin.shareableLink': { en: 'Shareable link' },
  'admin.inRoomQr': { en: 'In-room QR' },
  'admin.roomScreen': { en: 'room screen' },
  'admin.panelistView': { en: 'panelist view' },
  'admin.sessionDeactivated': { en: 'Session deactivated' },
  'admin.sessionIsLive': { en: 'Session is live' },
  'admin.hideLinks': { en: 'Hide links' },
  'admin.aCopyWithThe': { en: 'A copy with the same settings, facilitators and prepared questions — not active, not scheduled' },
  'admin.copiedEditTheCopy': { en: 'Copied — edit the copy to rename or schedule it' },
  'admin.emailLinks': { en: 'Email links' },
  'admin.endSession': { en: 'End session' },
  'admin.endThisSession': { en: 'End this session?' },
  'admin.ending': { en: 'Ending…' },
  'admin.emailSummary': { en: 'Email summary' },
  'admin.moveOutOfThe': { en: 'Move out of the list; restore any time from Archived sessions' },
  'admin.deleteThisSession': { en: 'Delete this session?' },
  'admin.deleteSession': { en: 'Delete session' },
  'admin.sessionDeleted': { en: 'Session deleted' },
  'admin.roomScreen2': { en: 'Room screen' },
  'admin.powerpointSlide': { en: 'PowerPoint slide' },
  'admin.replaceRoomScreenLink': { en: 'Replace room screen link' },
  'admin.replaceTheRoomScreen': { en: 'Replace the room screen link?' },
  'admin.theCurrentRoomScreen': { en: 'The current room screen link and PowerPoint slide link stop working, including on screens and slides already showing them. Copy the new links into those places. Participants are not affected.' },
  'admin.replaceLink': { en: 'Replace link' },
  'admin.newRoomScreenAnd': { en: 'New room screen and slide links created' },
  'admin.panelistView2': { en: 'Panelist view' },
  'admin.qaFacilitatorQueue': { en: 'QA Facilitator queue' },
  'admin.participantLink': { en: 'Participant link' },
  'admin.replaceParticipantLink': { en: 'Replace participant link' },
  'admin.replaceTheParticipantLink': { en: 'Replace the participant link?' },
  'admin.theOldLinkStops': { en: 'The old link stops working for anyone who has not joined yet. People already in the session can keep asking.' },
  'admin.newParticipantLinkCreated': { en: 'New participant link created' },
  'admin.inRoomSessionsHave': { en: 'In-room sessions have no participant link — people join by scanning the room screen.' },
  'admin.ifALinkShows': { en: 'If a link shows Google\'s "Sorry, unable to open the file at this time", the browser is signed into more than one Google account. Open the link in a private browsing window. Use one on the projector computer too.' },
  'admin.editSession': { en: 'Edit session' },
  'admin.newSession': { en: 'New session' },
  'admin.noQaFacilitatorsYet': { en: 'No QA Facilitators yet.' },
  'admin.sessionLogo': { en: 'Session logo' },
  'admin.usesTheOrganizationLogo': { en: 'Uses the organization logo' },
  'admin.sessionLogoSaved': { en: 'Session logo saved' },
  'admin.sessionLogoRemoved': { en: 'Session logo removed' },
  'admin.newEvent': { en: 'New event' },
  'admin.noQaFacilitatorsYet2': { en: 'No QA Facilitators yet. Add them on the People tab.' },
  'admin.noEventCoordinatorsYet': { en: 'No Event Coordinators yet. Add them on the People tab.' },
  'admin.eventLogo': { en: 'Event logo' },
  'admin.usesTheSiteLogo': { en: 'Uses the site logo' },
  'admin.eventLogoSaved': { en: 'Event logo saved' },
  'admin.eventLogoRemoved': { en: 'Event logo removed' },
  'admin.checking': { en: 'Checking…' },
  'admin.wholeApp': { en: 'Whole app' },
  'admin.thisEventHasNo': { en: 'This event has no sessions yet.' },
  'admin.chooseACsvFile': { en: 'Choose a CSV file or paste one first.' },
  'admin.eventSaved': { en: 'Event saved' },
  'admin.eventCreatedAddIts': { en: 'Event created — add its sessions' },
  'admin.sessionSaved': { en: 'Session saved' },
  'admin.sessionCreatedActivateIt': { en: 'Session created — activate it when you are ready' },
  'admin.anyoneWithThisLink': { en: 'Anyone with this link can ask a question.' },
  'admin.notAvailableInRoom': { en: 'Not available: in-room sessions are joined by scanning the room screen.' },
  'admin.googleDoesNotTell': { en: 'Google does not tell the app who is signed in from any other domain.' },
  'admin.createsOneAndSends': { en: 'creates one and sends them a set-your-password email.' },
  'admin.noneYet': { en: 'None yet' },
  'admin.languagesSaved': { en: 'Languages saved' },
  'admin.currentLogo': { en: 'Current logo' },
  'admin.noLogo': { en: 'No logo' },
  'admin.aKeyIsSaved': { en: 'A key is saved. Paste a new one to replace it; the key itself is never shown again.' },
  'admin.noKeyYetWithout': { en: 'No key yet. Without one, questions still arrive and can be answered — they are simply not grouped or translated.' },
  'admin.pasteAKeyFirst': { en: 'Paste a key first.' },
  'admin.geminiKeySaved': { en: 'Gemini key saved' },
  'admin.removeTheGeminiKey': { en: 'Remove the Gemini key?' },
  'admin.questionsWillStillArrive': { en: 'Questions will still arrive and can be answered, but nothing will be grouped or translated until a key is added again.' },
  'admin.geminiKeyRemoved': { en: 'Gemini key removed' },
  'admin.editedHere': { en: 'Edited here' },
  'admin.theBuiltInPrompt': { en: 'The built-in prompt' },
  'admin.promptSavedUsedFrom': { en: 'Prompt saved — used from the next request' },
  'admin.putTheBuiltIn': { en: 'Put the built-in prompt back?' },
  'admin.builtInPromptRestored': { en: 'Built-in prompt restored' },
  'admin.modelDefault': { en: 'Model default' },
  'admin.minimalFastest': { en: 'Minimal (fastest)' },
  'admin.highSlowest': { en: 'High (slowest)' },
  'admin.geminiSettingsSavedUsed': { en: 'Gemini settings saved — used from the next request' },
  'admin.geminiSettingsReset': { en: 'Gemini settings reset' },
  'admin.loadTestReadyRun': { en: 'Load test ready — run the command' },
  'admin.finishTheLoadTest': { en: 'Finish the load test?' },
  'admin.theTestEndpointIs': { en: 'The test endpoint is switched off, and its session and every test question are deleted.' },
  'admin.finishAndDelete': { en: 'Finish and delete' },
  'admin.loadTestFinishedAnd': { en: 'Load test finished and cleaned up' },
  'admin.removeSummaryRecipient': { en: 'Remove summary recipient?' },
  'admin.brandingSaved': { en: 'Branding saved' },
  'admin.logoSaved': { en: 'Logo saved' },
  'admin.removeTheLogo': { en: 'Remove the logo?' },
  'admin.pagesWillShowYour': { en: 'Pages will show your organization name instead.' },
  'admin.removeLogo': { en: 'Remove logo' },
  'admin.logoRemoved': { en: 'Logo removed' },
  'admin.couldNotReadThat': { en: 'Could not read that file.' },
  'admin.thatFileIsNot': { en: 'That file is not an image this browser can read.' },
  'admin.thatImageIsToo': { en: 'That image is too detailed to use as a logo. Try a simpler or smaller version.' },

  'admin.copied': { en: 'Copied' },
  'admin.details': { en: 'Details' },
  'admin.action': { en: 'Action' },
  'admin.who': { en: 'Who' },
  'admin.when': { en: 'When' },
  'admin.send': { en: 'Send' },
  'admin.restore': { en: 'Restore' },
  'admin.links': { en: 'Links' },
  'admin.duplicate': { en: 'Duplicate' },
  'admin.edit': { en: 'Edit' },
  'admin.archive': { en: 'Archive' },
  'admin.delete': { en: 'Delete' },
  'admin.copy': { en: 'Copy' },
  'admin.open': { en: 'Open' },
  'admin.notes': { en: 'Notes' },
  'admin.result': { en: 'Result' },
  'admin.session': { en: 'Session' },
  'admin.event': { en: 'Event' },
  'admin.row': { en: 'Row' },
  'admin.problem': { en: 'Problem' },
  'admin.skip': { en: 'Skip' },
  'admin.update': { en: 'Update' },
  'admin.updated': { en: 'Updated' },
  'admin.create': { en: 'Create' },
  'admin.created': { en: 'Created' },
  'admin.you': { en: 'You' },
  'admin.owner': { en: 'Owner' },
  'admin.remove': { en: 'Remove' },
  'admin.saved': { en: 'Saved' },
  'admin.reset': { en: 'Reset' },
  'admin.medium': { en: 'Medium' },
  'admin.low': { en: 'Low' },

  'mod.eventTeam': { en: 'Event team' },
  'mod.eventTeamDone': { en: 'Event team ✓' },
  'mod.alsoShownAnswerNow': { en: 'With Answer now, phones and the room screen show' },
  'mod.readOutFor': { en: 'Question to read out for {topic}' },
  'mod.mergeBusy': { en: 'Gemini is writing one question for this topic. This can take up to half a minute.' },
  'mod.rewriteWithGemini': { en: 'Rewrite with Gemini' },
  'mod.writeReadOut': { en: 'Write one question to read out' },
  'mod.mergeHint.one': { en: 'Gemini combines this {n} question into one. You can edit it.' },
  'mod.mergeHint.other': { en: 'Gemini combines these {n} questions into one. You can edit it.' },
  'mod.trTopicOnPhones': { en: 'Topic on phones' },
  'mod.trTopicIfShown': { en: 'Topic, if shown on phones' },
  'mod.trReadOut': { en: 'Read-out question' },
  'mod.moreActions': { en: 'More actions for {topic}' },
  'mod.groupingLate': { en: 'Grouping runs every minute. Questions still waiting? Press Group now, or run the health check on the Admin page.' },
  'mod.selectQuestion': { en: 'Select this question' },

  'panel.nowAnswering': { en: 'Now answering' },
  'panel.timerTitle': { en: 'Time on this question' },
  'panel.waiting': { en: 'Waiting for the facilitator to choose a question.' },
  'panel.ended': { en: 'This session has ended. Thank you.' },
  'panel.notStarted': { en: 'This session hasn\'t started yet.' },
  'panel.live': { en: 'Updates automatically' },
  'panel.stale': { en: 'Not updating — check the connection' },

  'present.waitingToStart': { en: 'Waiting for this session to start' },
  'present.codeRefreshes': { en: 'Code refreshes automatically' },
  'present.paused': { en: 'Questions are paused' },
  'present.lostConnection': { en: 'Lost connection — retrying' },
  'present.stale': { en: 'Not updating — check the internet connection. This code may have expired.' },
  'present.codeUpdated': { en: ' · code updated {at}' },

  'sheet.pageTitle': { en: '{event} — QR sheets' },
  'sheet.print': { en: 'Print' },
  'sheet.download': { en: 'Download QR images' },
  'sheet.downloadFallback': { en: 'Save each image below' },
  'sheet.intro.one': { en: '{n} page for {event}, one per shareable-link session. Print on letter or A4.' },
  'sheet.intro.other': { en: '{n} pages for {event}, one per shareable-link session. Print on letter or A4.' },
  'sheet.nothing': { en: 'No sessions in {event} use a shareable link, so there is nothing to print.' },
  'sheet.qr': { en: 'QR code' },
  'sheet.qrFor': { en: 'QR code for {name}' },
  'sheet.skipped': { en: 'Not printed (in-room sessions join by the changing code on the room screen): {names}.' },
  'sheet.saveByHand': { en: 'Right-click (or press and hold) each image to save it.' },

  'coord.title': { en: 'Event logistics' },
  'coord.pageTitle': { en: '{event} — event logistics' },
  'coord.loading': { en: 'Loading…' },
  'coord.adminLink': { en: 'Admin' },
  'coord.waiting': { en: '{n} waiting' },
  'coord.allSorted': { en: 'All sorted' },
  'coord.tally.one': { en: '{n} question about running the event' },
  'coord.tally.other': { en: '{n} questions about running the event' },
  'coord.lead': { en: 'Questions the audience asked about the event itself — rooms, timing, access, food, signage. They are also in each session’s queue, so a facilitator can answer from the stage; tick one here when it has been dealt with.' },
  'coord.answered': { en: 'Answered in the session' },
  'coord.putBack': { en: 'Put back' },
  'coord.sorted': { en: 'Sorted' },
  'coord.empty': { en: 'Nothing yet. Questions about rooms, timing, access or anything else about running the event will appear here as they are asked.' }
};

/** Pages that read BOOT.words. Ask.html is not one: participants get BOOT.text instead. */
const APP_TEXT_FOR = {
  'Admin.html': true,
  'Coordinator.html': true,
  'Home.html': true,
  'Moderate.html': true,
  'Panel.html': true,
  'Present.html': true,
  'Sheet.html': true
};

/** Fills {name} placeholders. Anything the catalog has no value for is left as it stands. */
function format_(text, vars) {
  if (!vars) return text;
  return String(text).replace(/\{(\w+)\}/g, function (whole, name) {
    return vars[name] === undefined || vars[name] === null ? whole : String(vars[name]);
  });
}

/**
 * Which plural form a count takes. English and Spanish agree (one / other); a language that
 * needs more forms adds itself here rather than to 27 call sites.
 */
function plural_(lang, n) {
  return Number(n) === 1 ? 'one' : 'other';
}

/** An app language code we actually have, or English. */
function appLanguageCode_(code) {
  return code && CONFIG.appLanguages[code] ? code : 'en';
}

/** The whole catalog in one language, English wherever that language has no wording yet. */
function wordsFor_(lang) {
  const code = appLanguageCode_(lang);
  const out = {};
  Object.keys(APP_TEXT).forEach(function (key) {
    out[key] = APP_TEXT[key][code] || APP_TEXT[key].en;
  });
  return out;
}

/** One phrase, for the server's own use (errors, emails). */
function t_(key, vars, lang) {
  const entry = APP_TEXT[key];
  if (!entry) throw new Error('Unknown phrase ' + key + '.');
  return format_(entry[appLanguageCode_(lang)] || entry.en, vars);
}

/** The language one person reads the app in. Set per person on the People tab. */
function appLanguage_(email) {
  if (email === undefined) email = currentEmail_();
  const saved = personLanguages_()[String(email || '').toLowerCase()];
  return appLanguageCode_(saved || siteLanguage_());
}

/** Everyone's chosen language, by address. */
function personLanguages_() {
  try {
    return JSON.parse(props_().getProperty('PEOPLE_LANG') || '{}') || {};
  } catch (err) {
    return {};
  }
}

/** The site's own language: what a room screen and anyone with no choice of their own reads. */
function siteLanguage_() {
  return appLanguageCode_(props_().getProperty('APP_LANGUAGE'));
}

/**
 * The language a room screen, slide and panelist view speak. Nobody is signed in at a venue
 * laptop, so it follows the session, then its event, then the site.
 */
function roomLanguage_(session) {
  if (session && session.roomLanguage) return appLanguageCode_(session.roomLanguage);
  const ev = session && session.eventId ? getEvent_(session.eventId) : null;
  if (ev && ev.roomLanguage) return appLanguageCode_(ev.roomLanguage);
  return siteLanguage_();
}
