/**
 * Question Desk server code: every word staff and the stage read, in each app language.
 * Apps Script runs every server file as one program; see Code.js for settings and routing.
 *
 * Two catalogs, split by who is reading, because they ship differently:
 *   UI_TEXT (text.js)  the audience. Every language goes to the page; the phone picks, because
 *                      there is no reader to ask.
 *   APP_TEXT (here)    staff, and the people on stage. The server knows who is reading, so it
 *                      resolves one language and sends only that, as BOOT.words.
 *
 * Keys are flat and dotted, and name a place, not a phrase: two screens that happen to say the
 * same English word still get their own key, because one Spanish word rarely fits both.
 * Languages are CONFIG.appLanguages, which is deliberately not CONFIG.languages — those names
 * are compared as values (participants.js, summaries.js) and must not grow entries.
 */

// ---------------------------------------------------------------- staff-facing text

const APP_TEXT = {
  'err.giveTheSessionAName': { en: 'Give the session a name.' },
  'err.theScheduledEndMustBe': { en: 'The scheduled end must be after the start.' },
  'err.theScheduledEndHasAlready': { en: 'The scheduled end has already passed. Saving it would end the session for good — check the date and AM/PM.' },
  'err.sessionAccentColorMustLook': { en: 'Session accent color must look like #1b5e5a.' },
  'err.thatListOfPreparedQuestions': { en: 'That list of prepared questions is too long.' },
  'err.thatEventNoLongerExists': { en: 'That event no longer exists.' },
  'err.sendTheSessionsInTheir': { en: 'Send the sessions in their new order.' },
  'err.thisSessionHasEndedAnd': { en: 'This session has ended and cannot be reopened.' },
  'err.thisSessionHasAlreadyEnded': { en: 'This session has already ended.' },
  'err.deactivateOrEndTheSession': { en: 'Deactivate or end the session before deleting it.' },
  'err.addAtLeastOneRecipient': { en: 'Add at least one recipient.' },
  'err.inRoomSessionsHaveNo': { en: 'In-room sessions have no shareable link — people join by scanning the room screen.' },
  'err.chooseAtLeastOneLink': { en: 'Choose at least one link to send.' },
  'err.enterAnEmailAddress': { en: 'Enter an email address.' },
  'err.theScriptOwnerIsAlways': { en: 'The script owner is always an administrator.' },
  'err.youCannotRemoveYourselfAsk': { en: 'You cannot remove yourself. Ask another administrator.' },
  'err.theTabIconMustBe': { en: 'The tab icon must be an https:// link to an image.' },
  'err.thatLooksLikeAGuest': { en: 'That looks like a guest page address. Put it in "Guest page address" and leave the Question Desk Google address blank.' },
  'err.theQuestionDeskGoogleAddress': { en: 'The Question Desk Google address must look like https://script.google.com/macros/s/…/exec — or leave it blank.' },
  'err.theLogoMustBeA': { en: 'The logo must be a PNG, JPEG or WebP image.' },
  'err.thatLogoIsTooLarge': { en: 'That logo is too large even after resizing.' },
  'err.thatQuestionIsNoLonger': { en: 'That question is no longer in this event.' },
  'err.thatFileIsTooLarge': { en: 'That file is too large to import.' },
  'err.theFileIsEmpty': { en: 'The file is empty.' },
  'err.theFileNeedsASession': { en: 'The file needs a "Session" column. Export sessions first to get the format.' },
  'err.noSessionName': { en: 'No session name.' },
  'err.giveTheEventAName': { en: 'Give the event a name.' },
  'err.eventNotFound': { en: 'Event not found.' },
  'err.sendTheEventsInTheir': { en: 'Send the events in their new order.' },
  'err.thisEventHasNoSessions': { en: 'This event has no sessions that haven\'t ended.' },
  'err.noQaFacilitatorsAreAssigned': { en: 'No QA Facilitators are assigned to this event or its sessions.' },
  'err.thisEventHasNoSessions2': { en: 'This event has no sessions yet.' },
  'err.temperatureMustBeBetween0': { en: 'Temperature must be between 0 and 1.' },
  'err.questionsPerGroupingRequestMust': { en: 'Questions per grouping request must be a whole number from 5 to 100.' },
  'err.unknownPrompt': { en: 'Unknown prompt.' },
  'err.thatPromptIsTooLong': { en: 'That prompt is too long: keep it under 8000 characters.' },
  'err.thatDoesNotLookLike': { en: 'That does not look like a Gemini API key. Copy it from aistudio.google.com.' },
  'err.notAllowed': { en: 'Not allowed.' },
  'err.groupingFailedGeminiReturnedNo': { en: 'Grouping failed: Gemini returned no assignments.' },
  'err.thatTopicHasNoQuestions': { en: 'That topic has no questions.' },
  'err.unknownStatus': { en: 'Unknown status.' },
  'err.chooseAPreparedQuestionTo': { en: 'Choose a prepared question to add.' },
  'err.thosePreparedQuestionsWereAlready': { en: 'Those prepared questions were already added or removed.' },
  'err.thatQuestionIsNoLonger2': { en: 'That question is no longer in the queue.' },
  'err.thatQuestionIsInA': { en: 'That question is in a topic now: show the topic on phones instead.' },
  'err.giveTheGroupATopic': { en: 'Give the group a topic name.' },
  'err.chooseTheQuestionsToGroup': { en: 'Choose the questions to group.' },
  'err.thoseQuestionsAreNoLonger': { en: 'Those questions are no longer in the queue.' },
  'err.chooseTheQuestionsToUngroup': { en: 'Choose the questions to ungroup.' },
  'err.chooseToKeepQuestionWording': { en: 'Choose to keep question wording, or remove it after 3, 6, 12 or 24 months.' },
  'err.onlyEndedSessionsCanBe': { en: 'Only ended sessions can be archived.' },
  'err.thatSessionIsAlreadyRestored': { en: 'That session is already restored.' },
  'err.archivedSessionNotFound': { en: 'Archived session not found.' },
  'err.youAreNotAnEvent': { en: 'You are not an Event Coordinator for this event.' },
  'err.onlyAdministratorsCanDoThat': { en: 'Only administrators can do that.' },
  'err.youAreNotAQa': { en: 'You are not a QA Facilitator for this session.' },
  'err.thisSessionHasEnded': { en: 'This session has ended.' },
  'err.runSetupFromTheApps': { en: 'Run setUp() from the Apps Script editor as the script owner.' },
  'err.theGuestPageAddressMust': { en: 'The guest page address must be an https:// link to the folder or page with the guest page files, without ? or #.' },

  'err.maxLengthRange': { en: 'Question length must be between 50 and {max} characters.' },
  'err.cooldownRange': { en: 'Time between questions must be between 0 and {max} seconds.' },
  'err.preparedTooMany': { en: 'Load at most {max} prepared questions per session.' },
  'err.preparedTooShort': { en: 'Prepared question is too short: {text}' },
  'err.preparedTooLong': { en: 'A prepared question is longer than {max} characters: {text}…' },
  'err.scheduleNotADate': { en: 'The scheduled {which} is not a valid date and time.' },
  'err.typeTheNameToConfirm': { en: 'Type the {what} name exactly to confirm: {name}' },
  'err.noFacilitatorsAssigned': { en: 'This session has no QA Facilitators assigned.' },
  'err.outsideDomain': { en: 'Only @{domain} accounts can sign in to this app. Google does not tell the app who is signed in from any other domain.' },
  'err.colorFormat': { en: '{label} must be a color like #1b5e5a.' },
  'err.csvNotADateTime': { en: '{label} "{value}" is not a date and time like 2026-10-03 18:30.' },
  'err.csvBadHour': { en: '{label} "{value}" has an hour that doesn\'t fit AM/PM.' },
  'err.csvNotRealDate': { en: '{label} "{value}" is not a real date and time.' },
  'err.csvYesNo': { en: '{label} should be yes or no, not "{value}".' },
  'err.csvTooManyRows': { en: 'Import at most {max} sessions at a time.' },
  'err.csvDuplicateRow': { en: 'The same session is already on row {row}.' },
  'err.csvAccess': { en: 'How people join should be room or link, not "{value}".' },
  'err.csvTheme': { en: 'Theme should be dark, light or contrast, not "{value}".' },
  'err.unknownLanguage': { en: 'Unknown language: {code}. Choose from {codes}.' },
  'err.tooManyLanguages': { en: 'Choose at most {max} languages, including English, so the room screen stays readable.' },
  'err.modelName': { en: 'Enter a Gemini model name, like {example}.' },
  'err.thinkingLevel': { en: 'Choose a thinking level for {task}.' },
  'err.promptNeeds': { en: 'The prompt must still contain {tokens}, or Question Desk has nothing to send. Put it back, or use Reset.' },
  'err.promptNeedsJoin': { en: ' and ' },
  'err.groupingFailed': { en: 'Grouping failed: {why}' },
  'err.groupingNoTopics': { en: 'Grouping failed: Gemini returned no usable topics for {n} question(s).' },
  'err.notAnEmail': { en: 'Not an email address: {value}' },
  'err.tooManyRecipients': { en: 'Send to at most {max} people at a time.' },
  'err.emailQuota': { en: 'Daily email quota reached ({left} left). Try again tomorrow.' },

  'notice.pick.title': { en: 'Choose a session' },
  'notice.pick.body': { en: 'Pick the session to open.' },
  'notice.pick.none': { en: 'You are not assigned to any open sessions.' },
  'notice.pick.active': { en: 'Active' },
  'notice.pick.inactive': { en: 'Not active' },
  'notice.pickEvent.title': { en: 'Choose an event' },
  'notice.pickEvent.body': { en: 'Pick the event to open.' },
  'notice.pickEvent.none': { en: 'You are not an Event Coordinator for any event.' },
  'notice.oldScreenLink.tab': { en: 'Room screen link out of date' },
  'notice.oldScreenLink.title': { en: 'This room screen link is out of date' },
  'notice.oldScreenLink.body': { en: 'Room screen and PowerPoint slide links changed. Ask whoever runs the session to copy the new one from the Admin page (Sessions → Links). To ask a question, scan the code on the screen in the room.' },
  'notice.noSession.tab': { en: 'Session not found' },
  'notice.noSession.title': { en: 'This room screen link is not valid' },
  'notice.noSession.body': { en: 'Check the link with whoever is running the session, or scan the code on the screen in the room to ask a question.' },
  'notice.denied.tab': { en: 'Not available' },
  'notice.denied.title': { en: 'This view is for QA Facilitators' },
  'notice.denied.body': { en: 'Sign in with an account listed as a QA Facilitator, or scan the code on the screen in the room to ask a question.' },

  'mail.summarySubject': { en: '{name} — questions summary' },
  'mail.summarySubjectEvent': { en: '{event}: {name} — questions summary' },
  'mail.summaryTitle': { en: '{name} — questions' },
  'mail.summaryCounts': { en: '{questions} questions in {topics} topics{dismissed}' },
  'mail.summaryDismissed': { en: ' · {n} dismissed' },
  'mail.summaryMeToo': { en: ' · {n} me too' },
  'mail.summaryShown': { en: ' · shown on phones' },
  'mail.summaryNotGrouped': { en: 'Not grouped' },
  'mail.summaryUntranslated': { en: 'Original wording — not translated' },
  'mail.summaryUntranslatedLang': { en: ' ({lang})' },
  'mail.summaryOriginal': { en: 'Original ({lang}): ' },
  'mail.summaryUnknownLanguage': { en: 'unknown language' },
  'mail.summarySingleMeToo': { en: '{n} me too · shown on phones' },

  'mail.linksSubject': { en: '{event} — your Question Desk sessions' },
  'mail.linksLead.one': { en: 'The session you are running in {event}. Each link opens that session\'s question queue, and needs your {domain} account.' },
  'mail.linksLead.other': { en: 'The {n} sessions you are running in {event}. Each link opens that session\'s question queue, and needs your {domain} account.' },
  'mail.linksQueue': { en: 'QA Facilitator queue' },
  'mail.eventSummarySubject': { en: '{event} — questions summary for the whole event' },
  'mail.eventSummaryTitle': { en: '{event} — questions' },
  'mail.eventQuestions': { en: ' · {n} questions' },
  'mail.reviewTitle': { en: 'What the questions say' },
  'mail.reviewSource': { en: 'Written by Gemini from {reviewed} of the {questions} asked across {sessions}. Read it as a starting point, not a verdict.' },
  'mail.reviewQuestions.one': { en: '{n} question' },
  'mail.reviewQuestions.other': { en: '{n} questions' },
  'mail.reviewSessions.one': { en: '{n} session' },
  'mail.reviewSessions.other': { en: '{n} sessions' },
  'mail.reviewThemes': { en: 'Themes worth acting on' },
  'mail.reviewNextTime': { en: 'Next time: {what}' },
  'mail.reviewLogistics': { en: 'Running the event' },
  'mail.reviewIndividual': { en: 'Questions about one person\'s situation' },
  'mail.reviewIndividualCount.one': { en: '{n} question was about somebody\'s own circumstances. {pattern}' },
  'mail.reviewIndividualCount.other': { en: '{n} questions were about somebody\'s own circumstances. {pattern}' },
  'mail.reviewAtScale': { en: 'For everyone in that position: {what}' },
  'mail.reviewSessionIdeas': { en: 'Sessions to consider next time' },
  'mail.reviewMissing': { en: 'The questions are below, but no review was written this time. {why}' },

  'ops.check.grouping': { en: 'Question grouping' },
  'ops.check.groupingNoTrigger': { en: 'The every-minute trigger is missing — run setUp().' },
  'ops.check.groupingFailures': { en: '{n} failed runs in a row: {why}' },
  'ops.check.working': { en: 'Working' },
  'ops.check.key': { en: 'Gemini API key' },
  'ops.check.keySet': { en: 'Set' },
  'ops.check.keyMissing': { en: 'Missing' },
  'ops.check.keyMissingHow': { en: 'Missing — add it under Admin → Health & testing → Gemini.' },
  'ops.check.quota': { en: 'Email quota' },
  'ops.check.quotaLeft': { en: '{n} left today' },
  'ops.check.quotaEmails': { en: '{n} emails left today' },
  'ops.check.storage': { en: 'Settings storage' },
  'ops.check.storageUsed': { en: '{pct}% of 500 KB used{advice}' },
  'ops.check.storageAdvice': { en: ' — archive or delete old sessions' },
  'ops.check.summariesOwed': { en: 'Summaries not sent' },
  'ops.check.model': { en: 'Gemini model {model}' },
  'ops.check.modelOk': { en: 'Responded in {ms} ms' },
  'ops.check.trigger': { en: 'Grouping and schedule trigger' },
  'ops.check.triggerOk': { en: 'Runs every minute' },
  'ops.check.triggerMissing': { en: 'Missing — run setUp() from the editor.' },
  'ops.check.sheet': { en: 'Submissions sheet' },
  'ops.check.sheetOk': { en: 'Reachable' },
  'ops.check.sheetMissing': { en: 'Some sheets are missing — run setUp() from the editor.' },
  'ops.check.address': { en: 'App address' },
  'ops.check.addressDev': { en: 'Points at the /dev test address — set the app address on the Branding tab.' },
  'ops.check.recent': { en: 'Recent grouping' },
  'ops.check.recentFailures': { en: '{n} failed runs in a row. Last error: {why}' },
  'ops.check.nothingYet': { en: 'Nothing grouped yet' },
  'ops.retentionOn': { en: 'Question wording is removed {months} months after a session ends.' },
  'ops.retentionOff': { en: 'Question wording is kept.' },
  'mail.weeklySubject': { en: 'Question Desk weekly report' },
  'mail.weeklySubjectProblems': { en: 'Question Desk weekly report — {n} need attention' },
  'mail.weeklyTitle': { en: 'Weekly report' },
  'mail.weeklyProblems.one': { en: '{n} thing needs attention.' },
  'mail.weeklyProblems.other': { en: '{n} things need attention.' },
  'mail.weeklyHealthy': { en: 'Everything looks healthy.' },
  'mail.weeklyUpcoming': { en: 'Coming up in the next 7 days' },
  'mail.weeklyNothingScheduled': { en: 'Nothing scheduled.' },
  'mail.weeklyActive': { en: 'Active now' },
  'mail.weeklyNoneActive': { en: 'No sessions are active.' },
  'mail.weeklyEnded': { en: 'Ended in the last 7 days' },
  'mail.weeklyNone': { en: 'None.' },
  'mail.weeklyAsked': { en: '{n} questions asked in the last 7 days. {retention}' },
  'mail.weeklyOff': { en: 'Turn this report off on the Admin page → Health &amp; testing.' },
  'mail.alertSubject': { en: 'Question Desk: {subject}' },
  'mail.alertGroupingFailing': { en: 'Question grouping is failing' },
  'mail.alertGroupingBody': { en: '<p>Questions are arriving but have not been grouped or translated for {n} runs in a row. QA Facilitators still see every question, ungrouped.</p><p><strong>Last error:</strong> {why}</p><p>Open the Admin page → Health and run a health check. A 404 usually means the Gemini model name ({model}) was retired; a 400 or 403 usually means the API key.</p>' },
  'mail.alertGroupingRecovered': { en: 'Question grouping recovered' },
  'mail.alertGroupingRecoveredBody': { en: '<p>Grouping and translation are working again.</p>' },

  'mail.linkAsk': { en: 'Ask a question' },
  'mail.linkAskNote': { en: 'Anyone with this link can submit a question anonymously. If it says "Sorry, unable to open the file", open it in a private browsing window.' },
  'mail.linkPresent': { en: 'Room screen' },
  'mail.linkPresentNote': { en: 'Open on the projector — no sign-in needed. Anyone with this link can see the join code, so share it only with the people running the room. Use a private browsing window on the projector computer, so no Google sign-in gets in the way.' },
  'mail.linkModerate': { en: 'QA Facilitator queue' },
  'mail.linkModerateNote': { en: 'Questions grouped by topic. Requires signing in with an assigned {domain} account.' },
  'mail.linksSessionSubject': { en: '{name} — Question Desk links' },

  'page.admin': { en: 'Question Desk admin' },
  'page.coordinator': { en: '{event} — event logistics' },
  'page.ask': { en: 'Ask a question' },
  'end.groupingFailed': { en: 'Final grouping failed, so some questions may be untranslated.' },
  'end.summaryFailed': { en: 'The summary email could not be sent ({why}). It will be retried automatically, or use Email summary.' },
  'queue.groupingFailing': { en: 'Grouping is failing' },
  'csv.alreadyExists': { en: 'Already exists; skipped.' },
  'csv.alreadyEnded': { en: 'Already exists and has ended; ended sessions can\'t be changed.' },
  'csv.notOnFacilitatorList': { en: 'Not on the QA Facilitator list, so not added: {names}. Add them on the People tab.' },
  'csv.newEvent': { en: 'New event "{name}" will be created.' },
  'csv.label.emailOnEnd': { en: 'Email summary' },
  'csv.label.guestRoom': { en: 'Guest page for room screen' },
  'csv.label.guestSlide': { en: 'Guest page for slide' },
  'csv.label.guestPanel': { en: 'Guest page for panelist view' },
  'csv.label.roomQuestions': { en: 'Room screen lists questions' },
  'csv.label.translatePrepared': { en: 'Translate prepared questions' },
  'csv.label.scheduledStart': { en: 'Scheduled start' },
  'csv.label.scheduledEnd': { en: 'Scheduled end' },
  'list.groupingRuns': { en: 'Question grouping runs every minute' },
  'list.runSetUp': { en: 'Run setUp() in the Apps Script editor.' },
  'list.geminiSetUp': { en: 'Gemini is set up' },
  'list.geminiNoKey': { en: 'No Gemini API key: add one under Health & testing.' },
  'list.geminiFailing': { en: 'Grouping failed {n} times in a row: {why}' },
  'list.emailQuota': { en: 'Email quota' },
  'list.emailsLeft': { en: '{n} emails left today' },
  'list.ended': { en: 'Ended' },
  'list.summaryEmailed': { en: 'Summary emailed {at}' },
  'list.summaryNotSent': { en: 'Summary not sent yet: {why}' },
  'list.activeTaking': { en: 'Active and taking questions' },
  'list.paused': { en: 'Questions are paused.' },
  'list.startsOnItsOwn': { en: 'Starts on its own' },
  'list.notActive': { en: 'Not active' },
  'list.activateWhenDoorsOpen': { en: 'Activate it on the Sessions tab when doors open.' },
  'list.endsOnItsOwn': { en: 'Ends on its own' },
  'list.noScheduledEnd': { en: 'No scheduled end' },
  'list.endByHand': { en: 'End it by hand afterwards.' },
  'list.facilitators': { en: 'QA Facilitators' },
  'list.nobodyCanRun': { en: 'Nobody can run the queue except administrators.' },
  'list.summaryEmail': { en: 'Summary email' },
  'list.notEmailed': { en: 'Not emailed when it ends.' },
  'list.summaryTo': { en: 'To {who}' },
  'list.nobodyWouldGet': { en: 'Turned on, but nobody would get it.' },
  'list.guestPage': { en: 'Guest page' },
  'list.guestRoom': { en: 'room screen' },
  'list.guestSlide': { en: 'PowerPoint slide' },
  'list.guestPanel': { en: 'panelist view' },
  'list.guestFor': { en: 'For {uses}' },
  'list.guestOff': { en: 'Off: browsers signed into several Google accounts may see "Sorry, unable to open the file".' },
  'list.prepared': { en: 'Prepared questions' },
  'list.reviewFailed': { en: 'The review could not be made: {why}' },
  'gem.label.grouping': { en: 'Grouping and translating questions' },
  'gem.label.translating': { en: 'Translating a question on its own' },
  'gem.label.merging': { en: 'Writing a topic\'s read-out question' },
  'gem.label.review': { en: 'Reviewing an event afterwards' },
  'gem.noKeyYet': { en: 'No Gemini API key yet: add one above.' },
  'gem.noKey': { en: 'No Gemini API key: an administrator can add one under Health & testing.' },
  'gem.unreachable': { en: 'Could not reach Gemini: {why}' },
  'gem.notSetUp': { en: 'Gemini isn\'t set up: an administrator needs to add the API key.' },
  'gem.busy': { en: 'Gemini is busy or out of quota. Try again in a minute.' },
  'gem.modelGone': { en: 'The Gemini model is no longer available. An admin needs to update Question Desk.' },
  'gem.noAnswer': { en: 'Gemini didn\'t answer. Try again in a moment.' },
  'gem.refused': { en: 'Gemini refused the request ({status}). An admin can run the health check on the Admin page.' },
  'gem.badAnswer': { en: 'Gemini\'s answer couldn\'t be used. Try again.' },
  'gem.noQuestionsToMerge': { en: 'This topic has no questions left to merge.' },
  'gem.noQuestionsToReview': { en: 'This event has no questions to review yet.' },
  'gem.hintModelGone': { en: ' — model {model} not found; it may have been retired. Choose another model under Admin → Health → Gemini.' },
  'gem.hintRateLimited': { en: ' — rate limited or out of quota.' },
  'gem.hintKeyRejected': { en: ' — the API key was rejected or the request is invalid.' },
  'gem.httpError': { en: 'Gemini {code}{hint} {body}' },
  'gem.parseFailed': { en: 'Could not parse Gemini response: {why}' },

  'err.notAnAppLanguage': { en: 'Not an app language: {code}' },
  'err.tooManyPersonLanguages': { en: 'Too many people have a language of their own to store. Remove someone first.' },

  'wp.err.unknownPage': { en: 'Unknown page.' },
  'wp.err.needsOriginalQuestion': { en: 'The file needs an "Original question" column. Use the CSV from a Question Desk summary email.' },
  'wp.err.noQuestion': { en: 'No question.' },
  'wp.err.keyInConfig': { en: 'The key is set in wp-config.php (QD_GEMINI_API_KEY). Change it there.' },
  'wp.err.retentionRange': { en: 'Keep question wording for between 0 and 120 months.' },
  'wp.err.modelName': { en: 'That model name does not look like a Gemini model.' },
  'wp.err.wordpressAdmins': { en: 'WordPress administrators always manage Question Desk. Change their role in Users.' },
  'wp.err.logoNotSaved': { en: 'The logo could not be saved.' },
  'wp.err.noRecipientsYet': { en: 'Add Session Summary Email Recipients on the People tab first.' },
  'wp.err.busy': { en: 'Question Desk is busy. Try again in a moment.' },

  'shared.dialog.ok': { en: 'OK' },
  'shared.dialog.typePrompt': { en: 'To confirm, type ' },
  'shared.failed': { en: 'Something went wrong.' },

  'home.staff.heading': { en: 'For staff' },
  'home.staff.none': { en: 'No open sessions assigned to you.' },
  'home.staff.admin': { en: 'Open the admin page' },
  'home.staff.signIn': { en: 'QA Facilitators and administrators: {link} with your {domain} account.' },
  'home.staff.signInLink': { en: 'sign in' },
  'home.session.active': { en: 'Active' },
  'home.session.inactive': { en: 'Not active' },
  'home.link.present': { en: 'Room screen' },
  'home.link.queue': { en: 'Queue' },

  'mod.title': { en: 'Question queue' },
  'mod.pageTitle': { en: 'QA - {name}' },
  'mod.pageTitleRoom': { en: 'QA - {name} ({room})' },
  'mod.switchSession': { en: 'Switch session' },
  'mod.optionEnded': { en: ' (ended)' },
  'mod.optionInactive': { en: ' (not active)' },
  'mod.loading': { en: 'Loading…' },
  'mod.roomScreen': { en: 'Room screen' },
  'mod.panelLink': { en: 'Panelist view' },
  'mod.panelLinkTitle': { en: 'The question being answered, large, for the panel table' },
  'mod.shortcuts': { en: 'Shortcuts' },
  'mod.shortcutsTitle': { en: 'Keyboard shortcuts (press ?)' },
  'mod.admin': { en: 'Admin' },
  'mod.endedNotice': { en: 'This session has ended. The queue is read-only.' },
  'mod.selectedRegion': { en: 'Selected questions' },
  'mod.selGroup': { en: 'Group as…' },
  'mod.selUngroup': { en: 'Ungroup' },
  'mod.selAnswered': { en: 'Answered' },
  'mod.selDismiss': { en: 'Dismiss' },
  'mod.selClear': { en: 'Clear' },
  'mod.selCount.one': { en: '{n} question selected' },
  'mod.selCount.other': { en: '{n} questions selected' },
  'mod.toggleTitle': { en: 'Click to pause or resume new questions' },
  'mod.accepting': { en: 'Accepting questions' },
  'mod.paused': { en: 'Paused — not accepting questions' },
  'mod.groupNow': { en: 'Group now' },
  'mod.groupNowTitle': { en: 'Group and translate waiting questions now, even when automatic grouping is off' },
  'mod.grouping': { en: 'Grouping…' },
  'mod.groupingFailed': { en: 'Grouping failed — retry' },
  'mod.autoGroup': { en: 'Group automatically' },
  'mod.autoGroupTitle': { en: 'Every minute, Gemini groups new questions into topics. Off: questions are still translated, and you group them yourself.' },
  'mod.autoShow': { en: 'Show on phones when answering' },
  'mod.autoShowTitle': { en: 'Answer now also shows the topic on participants\' phones' },
  'mod.roomQuestions': { en: 'List on the room screen' },
  'mod.roomQuestionsTitle': { en: 'The room screen lists what\'s on participants\' phones, most Me too first' },
  'mod.originals': { en: 'Show original wording' },
  'mod.prepared': { en: 'Prepared questions' },
  'mod.dismissedBox': { en: 'Dismissed' },
  'mod.empty': { en: 'Waiting for the first question.' },
  'mod.groupDialogTitle': { en: 'Group questions' },
  'mod.groupHint': { en: 'Type a new topic, or pick one that exists to add these questions to it.' },
  'mod.topicName': { en: 'Topic name' },
  'mod.groupOk': { en: 'Group' },
  'mod.cancel': { en: 'Cancel' },
  'mod.pillActive': { en: 'Active' },
  'mod.pillEnded': { en: 'Ended' },
  'mod.pillInactive': { en: 'Not active' },
  'mod.tally': { en: '{questions} across {topics}' },
  'mod.tallyQuestions.one': { en: '{n} question' },
  'mod.tallyQuestions.other': { en: '{n} questions' },
  'mod.tallyTopics.one': { en: '{n} topic' },
  'mod.tallyTopics.other': { en: '{n} topics' },
  'mod.saveFailed': { en: 'That change didn\'t save{detail} — reloaded the queue' },
  'mod.groupingDown': { en: 'Automatic grouping isn\'t working right now, so new questions aren\'t grouped or translated. Until it recovers, they\'re sorted below by a word they share. ({detail})' },
  'mod.looseMentions': { en: 'Not yet grouped · mentions “{word}”' },
  'mod.looseOther': { en: 'Not yet grouped · other questions' },
  'mod.notYetGrouped': { en: 'Not yet grouped' },
  'mod.questionsGroup': { en: 'Questions' },
  'mod.logistics': { en: 'About running the event: it is with the Event Coordinators as well as you.' },
  'mod.logisticsSorted': { en: 'About running the event. The Event Coordinators have sorted it.' },
  'mod.addToQueue': { en: 'Add to queue' },
  'mod.restore': { en: 'Restore' },
  'mod.readOut': { en: 'Read out' },
  'mod.save': { en: 'Save' },
  'mod.edit': { en: 'Edit' },
  'mod.remove': { en: 'Remove' },
  'mod.writeItYourself': { en: 'Write it yourself' },
  'mod.mergeBadAnswer': { en: 'Gemini\'s answer couldn\'t be used. Try again.' },
  'mod.mergeUnreachable': { en: 'Couldn\'t reach Question Desk ({detail}). Try again.' },
  'mod.connectionProblem': { en: 'connection problem' },
  'mod.mergeFailed': { en: 'Couldn\'t write it: {why}' },
  'mod.translations': { en: 'Translations · {names}' },
  'mod.topicCount.one': { en: '{n} question' },
  'mod.topicCount.other': { en: '{n} questions' },
  'mod.topicCountDone.one': { en: '{n} question · all answered' },
  'mod.topicCountDone.other': { en: '{n} questions · all answered' },
  'mod.meToo': { en: ' · +{n} me too' },
  'mod.answeringNow': { en: 'Answering now' },
  'mod.answeringNowTimer': { en: 'Answering now · {time}' },
  'mod.answerNow': { en: 'Answer now' },
  'mod.stopAnswering': { en: 'Stop answering' },
  'mod.answerNowTitle': { en: 'Put this topic on the room screen and participants\' phones as the one being answered' },
  'mod.stopAnsweringTitle': { en: 'Take this topic off the room screen and participants\' phones' },
  'mod.answerNowQuestionTitle': { en: 'Show this question on the room screen and phones as the one being answered' },
  'mod.onPhones': { en: 'On phones ✓' },
  'mod.showOnPhones': { en: 'Show on phones' },
  'mod.onPhonesTitle': { en: 'Participants can see this topic and tap Me too. Click to hide it from phones.' },
  'mod.showOnPhonesTitle': { en: 'Let participants see this topic label and tap Me too' },
  'mod.phonesOn': { en: 'Phones ✓' },
  'mod.phones': { en: 'Phones' },
  'mod.phonesOnTitle': { en: 'Participants can see this question and tap Me too. Click to hide it from phones.' },
  'mod.phonesTitle': { en: 'Let participants see this question (translated into their language) and tap Me too' },
  'mod.dismissAll.one': { en: 'Dismiss all {n} question' },
  'mod.dismissAll.other': { en: 'Dismiss all {n} questions' },
  'mod.dismissTopicTitle': { en: 'Dismiss this topic?' },
  'mod.dismissTopicBody.one': { en: 'All {n} question under "{topic}" move to Dismissed at the bottom of the page and come off participants\' phones. You can restore them.' },
  'mod.dismissTopicBody.other': { en: 'All {n} questions under "{topic}" move to Dismissed at the bottom of the page and come off participants\' phones. You can restore them.' },
  'mod.dismissAllOk': { en: 'Dismiss all' },
  'mod.answeredTag': { en: '✓ Answered' },
  'mod.answered': { en: 'Answered' },
  'mod.reopen': { en: 'Reopen' },
  'mod.answeredTitle': { en: 'Mark this question as answered' },
  'mod.reopenTitle': { en: 'Mark as not answered yet' },
  'mod.dismiss': { en: 'Dismiss' },
  'mod.dismissTitle': { en: 'Move to Dismissed at the bottom of the page' },
  'mod.lostConnection': { en: 'Lost connection — retrying' },
  'mod.notUpdating': { en: 'Not updating — check the connection' },
  'mod.updated': { en: 'Updated {at}' },
  'mod.keysTitle': { en: 'Keyboard shortcuts' },
  'mod.keysOk': { en: 'Got it' },
  'mod.keys.next': { en: 'Next question' },
  'mod.keys.nextPress': { en: 'J or ↓' },
  'mod.keys.prev': { en: 'Previous question' },
  'mod.keys.prevPress': { en: 'K or ↑' },
  'mod.keys.tick': { en: 'Tick the question (then Group as…, Ungroup, Answered or Dismiss)' },
  'mod.keys.answered': { en: 'Answered (or Reopen)' },
  'mod.keys.dismiss': { en: 'Dismiss' },
  'mod.keys.live': { en: 'Answer now / Stop answering for its topic' },
  'mod.keys.phones': { en: 'Show on or hide from phones (a question not in a topic, or else its topic)' },
  'mod.keys.merge': { en: 'Write (or rewrite) one question to read out for the topic' },
  'mod.keys.group': { en: 'Group now' },
  'mod.keys.originals': { en: 'Show original wording' },
  'mod.keys.clear': { en: 'Clear the selection' },
  'mod.keys.list': { en: 'This list' },

  'admin.top.questionDeskAdministration': { en: 'Question Desk Administration' },
  'admin.top.sessions': { en: 'Sessions' },
  'admin.top.people': { en: 'People' },
  'admin.top.branding': { en: 'Branding' },
  'admin.top.activity': { en: 'Activity' },
  'admin.top.healthTesting': { en: 'Health & testing' },
  'admin.sessions.newEvent': { en: 'New event' },
  'admin.sessions.newSession': { en: 'New session' },
  'admin.sessions.exportCsv': { en: 'Export CSV' },
  'admin.sessions.importCsv': { en: 'Import CSV' },
  'admin.sessions.sessionsCsv': { en: 'Sessions CSV' },
  'admin.sessions.exportCopy': { en: 'Copy' },
  'admin.sessions.exportClose': { en: 'Close' },
  'admin.sessions.checklistTitle': { en: 'Day-of checklist' },
  'admin.sessions.checklistRefresh': { en: 'Check again' },
  'admin.sessions.checklistClose': { en: 'Close' },
  'admin.sessions.importSessionsFromCsv': { en: 'Import sessions from CSV' },
  'admin.sessions.whenASessionAlready': { en: 'When a session already exists (same name, start and end — or same name when it has no times)' },
  'admin.sessions.importCheck': { en: 'Check file' },
  'admin.sessions.importGo': { en: 'Import' },
  'admin.sessions.importCancel': { en: 'Cancel' },
  'admin.sessions.eventFormTitle': { en: 'New event' },
  'admin.sessions.evname.hint': { en: 'Spring Family Conference 2027' },
  'admin.sessions.groupsTheSessionsHeld': { en: 'Groups the sessions held at one event, such as a conference with several rooms.' },
  'admin.sessions.qaFacilitatorsForEvery': { en: 'QA Facilitators for every session in this event' },
  'admin.sessions.theyCanRunThe': { en: 'They can run the queue for all of this event\'s sessions. Sessions can add more of their own. (Summaries go to the Session Summary Email Recipients on the People tab.)' },
  'admin.sessions.eventCoordinators': { en: 'Event Coordinators' },
  'admin.sessions.theyGetThisEvent': { en: 'They get this event\'s own portal: every question the audience asks about running it — rooms, timing, access, food — from all its sessions. Add people to the role on the People tab first.' },
  'admin.sessions.languages': { en: 'Languages' },
  'admin.sessions.eventBrandingOptional': { en: 'Event branding (optional)' },
  'admin.sessions.overridesTheSiteBranding': { en: 'Overrides the site branding for this event\'s sessions. Leave a field blank to use the site\'s. A session can still set its own name, color and logo.' },
  'admin.sessions.accentColor': { en: 'Accent color' },
  'admin.sessions.evaccent.says': { en: 'Event accent color' },
  'admin.sessions.roomScreenBackgroundDark': { en: 'Room screen background — dark' },
  'admin.sessions.evdark.says': { en: 'Event dark background' },
  'admin.sessions.roomScreenBackgroundLight': { en: 'Room screen background — light' },
  'admin.sessions.evlight.says': { en: 'Event light background' },
  'admin.sessions.logo': { en: 'Logo' },
  'admin.sessions.evlogoremove': { en: 'Remove event logo' },
  'admin.sessions.evlogolater': { en: 'Save the event first, then edit it to add a logo.' },
  'admin.sessions.saveEvent': { en: 'Save event' },
  'admin.sessions.cancelEvent': { en: 'Cancel' },
  'admin.sessions.formTitle': { en: 'New session' },
  'admin.sessions.forAdministratorsAndQa': { en: 'For administrators and QA Facilitators, e.g. "Family night — Sept".' },
  'admin.sessions.froom.hint': { en: 'Ballroom A' },
  'admin.sessions.whereItHappensShown': { en: 'Where it happens. Shown to staff and in their emails; participants never see it.' },
  'admin.sessions.howPeopleJoin': { en: 'How people join' },
  'admin.sessions.roomScreenTheme': { en: 'Room screen theme' },
  'admin.sessions.useTheGuestPage': { en: 'Use the guest page for' },
  'admin.sessions.avoidsGoogleSSorry': { en: 'Avoids Google\'s "Sorry, unable to open the file" on phones and browsers signed into several Google accounts. Unticked opens Google\'s address directly.' },
  'admin.sessions.guestPageAddressFor': { en: 'Guest page address for this session (optional)' },
  'admin.sessions.fguesturl.hint': { en: 'Uses the address on the Branding tab' },
  'admin.sessions.leaveBlankToUse': { en: 'Leave blank to use the organization\'s guest page. Fill in to use another site, such as a partner\'s. A shareable questions link uses the guest page when Room screen or PowerPoint slide is ticked.' },
  'admin.sessions.fprepared.hint': { en: 'One question per line' },
  'admin.sessions.loadedAheadOfTime': { en: 'Loaded ahead of time and kept out of sight. A QA Facilitator adds each one to the queue when it\'s useful. Saving replaces the ones not yet added.' },
  'admin.sessions.scheduleOptional': { en: 'Schedule (optional)' },
  'admin.sessions.checkedEveryMinuteEnding': { en: 'Checked every minute. Ending sends the summary if the box above is ticked. You can still start, stop and end by hand.' },
  'admin.sessions.sessionBrandingOptional': { en: 'Session branding (optional)' },
  'admin.sessions.forPartnerEventsLeave': { en: 'For partner events. Leave blank to use your organization\'s branding.' },
  'admin.sessions.accentColor2': { en: 'Accent color' },
  'admin.sessions.faccent.says': { en: 'Session accent color' },
  'admin.sessions.logo2': { en: 'Logo' },
  'admin.sessions.flogoremove': { en: 'Remove session logo' },
  'admin.sessions.flogolater': { en: 'Save the session first, then edit it to add a logo.' },
  'admin.sessions.qaFacilitatorsForThis': { en: 'QA Facilitators for this session' },
  'admin.sessions.administratorsCanRunEvery': { en: 'Administrators can run every session. Add people to the QA Facilitator list on the People tab.' },
  'admin.sessions.saveSession': { en: 'Save session' },
  'admin.sessions.cancelSession': { en: 'Cancel' },
  'admin.people.administrators': { en: 'Administrators' },
  'admin.people.canCreateAndRun': { en: 'Can create and run sessions, manage people, and change branding.' },
  'admin.people.nameDomainOrg': { en: 'name@domain.org' },
  'admin.people.administratorEmail': { en: 'Administrator email' },
  'admin.people.add': { en: 'Add' },
  'admin.people.qaFacilitators': { en: 'QA Facilitators' },
  'admin.people.runTheQueueFor': { en: 'Run the queue for the sessions they are assigned to: group, merge, approve topics for phones, and mark questions answered.' },
  'admin.people.nameDomainOrg2': { en: 'name@domain.org' },
  'admin.people.qaFacilitatorEmail': { en: 'QA Facilitator email' },
  'admin.people.add2': { en: 'Add' },
  'admin.people.eventCoordinators': { en: 'Event Coordinators' },
  'admin.people.seeTheQuestionsAbout': { en: 'See the questions about running an event — rooms, timing, access, food — in their own portal, for the events they are assigned to.' },
  'admin.people.nameDomainOrg3': { en: 'name@domain.org' },
  'admin.people.eventCoordinatorEmail': { en: 'Event Coordinator email' },
  'admin.people.add3': { en: 'Add' },
  'admin.people.sessionSummaryEmailRecipients': { en: 'Session Summary Email Recipients' },
  'admin.people.summaryHint': { en: 'Get every session\'s questions summary when it ends. Anyone can be added, even outside your organization.' },
  'admin.people.nameDomainOrg4': { en: 'name@domain.org' },
  'admin.people.sessionSummaryEmailRecipient': { en: 'Session summary email recipient' },
  'admin.people.add4': { en: 'Add' },
  'admin.branding.languages': { en: 'Languages' },
  'admin.branding.saveLangs': { en: 'Save languages' },
  'admin.branding.branding': { en: 'Branding' },
  'admin.branding.shownBesideTheLogo': { en: 'Shown beside the logo and as the sender name on emails.' },
  'admin.branding.accentColor': { en: 'Accent color' },
  'admin.branding.baccentpick.says': { en: 'Pick accent color' },
  'admin.branding.baccent.says': { en: 'Accent color hex' },
  'admin.branding.usedForButtonsOn': { en: 'Used for buttons on the participant page.' },
  'admin.branding.oneLineOnThe': { en: 'One line on the landing page and participant page, e.g. "Thank you for joining us tonight."' },
  'admin.branding.websiteOrContactLine': { en: 'Website or contact line on every page and email.' },
  'admin.branding.roomScreenBackgroundDark': { en: 'Room screen background — dark' },
  'admin.branding.bbgdark.says': { en: 'Dark background' },
  'admin.branding.roomScreenBackgroundLight': { en: 'Room screen background — light' },
  'admin.branding.bbglight.says': { en: 'Light background' },
  'admin.branding.bfavicon.hint': { en: 'https://your-site.org/icon.png' },
  'admin.branding.aLinkToA': { en: 'A link to a square PNG on your website. Google only accepts a public image link here, not an upload.' },
  'admin.branding.bguest.hint': { en: 'https://djsincla.github.io/question-desk/join/' },
  'admin.branding.advanced': { en: 'Advanced' },
  'admin.branding.saveBranding': { en: 'Save branding' },
  'admin.branding.logo': { en: 'Logo' },
  'admin.branding.removeLogo': { en: 'Remove logo' },
  'admin.branding.resizedInYourBrowser': { en: 'Resized in your browser before upload so pages stay fast on venue wifi. A wide logo on a transparent or white background works best.' },
  'admin.activity.activityLog': { en: 'Activity log' },
  'admin.activity.actSearch.hint': { en: 'Search people, actions, sessions…' },
  'admin.activity.actSearch.says': { en: 'Search the activity log' },
  'admin.activity.actTarget.says': { en: 'Show one session or event' },
  'admin.activity.actRefresh': { en: 'Refresh' },
  'admin.health.healthCheck': { en: 'Health check' },
  'admin.health.testsTheGeminiKey': { en: 'Tests the Gemini key and model, the every-minute trigger, the sheet, email quota and the app address. Admins are also emailed automatically if grouping fails 3 minutes in a row.' },
  'admin.health.runHealth': { en: 'Run health check' },
  'admin.health.sgrouping': { en: 'Last grouping' },
  'admin.health.squota': { en: 'Emails left today' },
  'admin.health.ssheet': { en: 'Submissions sheet' },
  'admin.health.dataAndReports': { en: 'Data and reports' },
  'admin.health.keepIt': { en: 'Keep it' },
  'admin.health.removeIt3Months': { en: 'Remove it 3 months after a session ends' },
  'admin.health.removeIt6Months': { en: 'Remove it 6 months after a session ends' },
  'admin.health.removeIt12Months': { en: 'Remove it 12 months after a session ends' },
  'admin.health.removeIt24Months': { en: 'Remove it 24 months after a session ends' },
  'admin.health.removingReplacesEachQuestion': { en: 'Removing replaces each question\'s original wording, its translation and merged questions with a note. Topics, languages, answered status, times and counts stay, so summaries and reports still add up. It can\'t be undone.' },
  'admin.health.settingsStorage': { en: 'Settings storage' },
  'admin.health.opssave': { en: 'Save' },
  'admin.health.opsreport': { en: 'Send me the weekly report now' },
  'admin.health.loadTest': { en: 'Load test' },
  'admin.health.simulatesAFullRoom': { en: 'Simulates a full room submitting at once, through the same code path phones use, against a throwaway session. Run it before an event, not during one.' },
  'admin.health.startLoad': { en: 'Start load test' },
  'admin.health.copyLoad': { en: 'Copy command' },
  'admin.health.stopLoad': { en: 'Finish and delete test data' },
  'admin.health.prompts': { en: 'Prompts' },
  'admin.health.exactlyWhatQuestionDesk': { en: 'Exactly what Question Desk asks Gemini, for each thing it does. Edit it to suit your audience; changes apply to the very next request. The rules underneath each prompt are always added and can\'t be edited — they are what keeps a question from being treated as an instruction, keeps topic labels in one language so questions group across languages, and keeps criticism unsoftened.' },
  'admin.health.promptsave': { en: 'Save prompt' },
  'admin.health.promptreset': { en: 'Reset to the built-in one' },
  'admin.health.alwaysAddedWhateverYou': { en: 'Always added, whatever you write' },
  'admin.health.gemini': { en: 'Gemini' },
  'admin.health.howQuestionDeskAsks': { en: 'How Question Desk asks Gemini to group, merge and translate. Saved changes apply to the very next request — no redeploy. More thinking can group and translate messy or mixed-language questions better, but takes longer; less thinking answers faster.' },
  'admin.health.gemkey.hint': { en: 'Paste a new key to replace it' },
  'admin.health.gemkeysave': { en: 'Save key' },
  'admin.health.gemkeyclear': { en: 'Remove key' },
  'admin.health.everyMinuteInThe': { en: 'Every minute, in the background. Quality matters most here.' },
  'admin.health.mergeIntoOneQuestion': { en: '"Merge into one question": a facilitator is waiting.' },
  'admin.health.showOnPhonesAnswer': { en: 'Show on phones, Answer now on one question, prepared questions.' },
  'admin.health.01LowerKeeps': { en: '0–1. Lower keeps topics and translations consistent and literal; 0–0.3 suits Question Desk.' },
  'admin.health.5100SmallerAnswers': { en: '5–100. Smaller answers sooner; larger groups a busy room in fewer requests.' },
  'admin.health.gemsave': { en: 'Save' },
  'admin.health.gemtest': { en: 'Try these settings' },
  'admin.health.gemreset': { en: 'Reset to defaults' },
  'admin.health.emailTitle': { en: 'Email links' },
  'admin.health.eto.hint': { en: 'one@example.org, two@example.org' },
  'admin.health.separateAddressesWithCommas': { en: 'Separate addresses with commas or new lines. Each person gets their own email.' },
  'admin.health.include': { en: 'Include' },
  'admin.health.esend': { en: 'Send' },
  'admin.health.ecancel': { en: 'Cancel' },
  'admin.health.dialogOk': { en: 'OK' },
  'admin.health.dialogCancel': { en: 'Cancel' },

  'admin.somethingWentWrong': { en: 'Something went wrong.' },
  'admin.selectedPressCtrlCmd': { en: 'Selected — press Ctrl/Cmd+C to copy' },
  'admin.allSessionsAndEvents': { en: 'All sessions and events' },
  'admin.loading': { en: 'Loading…' },
  'admin.sessionOrEvent': { en: 'Session or event' },
  'admin.nothingMatches': { en: 'Nothing matches.' },
  'admin.noWaitBetweenQuestions': { en: 'no wait between questions' },
  'admin.notActive': { en: 'Not active' },
  'admin.expandAllEvents': { en: 'Expand all events' },
  'admin.collapseAllEvents': { en: 'Collapse all events' },
  'admin.noEventsOrSessions': { en: 'No events or sessions yet. Create an event for a conference or meeting, then add its sessions.' },
  'admin.dragOrUseTo': { en: 'Drag ⋮⋮ or use ▲ ▼ to change the order of sessions within an event.' },
  'admin.notInAnEvent': { en: 'Not in an event' },
  'admin.usesTheSiteBranding': { en: 'Uses the site branding. Edit a session to put it in an event.' },
  'admin.moveEventUp': { en: 'Move event up' },
  'admin.moveEventDown': { en: 'Move event down' },
  'admin.showOrHideThis': { en: 'Show or hide this event\'s sessions' },
  'admin.ownBranding': { en: 'own branding' },
  'admin.siteBranding': { en: 'site branding' },
  'admin.addSession': { en: 'Add session' },
  'admin.editEvent': { en: 'Edit event' },
  'admin.emailQaFacilitators': { en: 'Email QA Facilitators' },
  'admin.noQaFacilitatorsAssigned': { en: 'No QA Facilitators assigned to this event or its sessions' },
  'admin.emailQaFacilitatorsTheir': { en: 'Email QA Facilitators their links?' },
  'admin.more': { en: 'More ▾' },
  'admin.dayOfChecklist': { en: 'Day-of checklist' },
  'admin.eventCoordinatorPortal': { en: 'Event Coordinator portal' },
  'admin.printQrSheets': { en: 'Print QR sheets' },
  'admin.aPrintablePageWith': { en: 'A printable page with the QR code for each shareable-link session' },
  'admin.emailSummaryForThe': { en: 'Email summary for the whole event' },
  'admin.duplicateEvent': { en: 'Duplicate event' },
  'admin.deleteEvent': { en: 'Delete event' },
  'admin.deleteThisEvent': { en: 'Delete this event?' },
  'admin.itsBrandingAndLogo': { en: 'Its branding and logo are deleted.' },
  'admin.eventDeleted': { en: 'Event deleted' },
  'admin.noSessionsYetUse': { en: 'No sessions yet. Use Add session.' },
  'admin.orderSaved': { en: 'Order saved' },
  'admin.dragToReorder': { en: 'Drag to reorder' },
  'admin.loadTest': { en: 'Load test' },
  'admin.shareableLink': { en: 'Shareable link' },
  'admin.inRoomQr': { en: 'In-room QR' },
  'admin.roomScreen': { en: 'room screen' },
  'admin.panelistView': { en: 'panelist view' },
  'admin.sessionDeactivated': { en: 'Session deactivated' },
  'admin.sessionIsLive': { en: 'Session is live' },
  'admin.hideLinks': { en: 'Hide links' },
  'admin.aCopyWithThe': { en: 'A copy with the same settings, facilitators and prepared questions — not active, not scheduled' },
  'admin.copiedEditTheCopy': { en: 'Copied — edit the copy to rename or schedule it' },
  'admin.emailLinks': { en: 'Email links' },
  'admin.endSession': { en: 'End session' },
  'admin.endThisSession': { en: 'End this session?' },
  'admin.ending': { en: 'Ending…' },
  'admin.emailSummary': { en: 'Email summary' },
  'admin.moveOutOfThe': { en: 'Move out of the list; restore any time from Archived sessions' },
  'admin.deleteThisSession': { en: 'Delete this session?' },
  'admin.deleteSession': { en: 'Delete session' },
  'admin.sessionDeleted': { en: 'Session deleted' },
  'admin.roomScreen2': { en: 'Room screen' },
  'admin.powerpointSlide': { en: 'PowerPoint slide' },
  'admin.replaceRoomScreenLink': { en: 'Replace room screen link' },
  'admin.replaceTheRoomScreen': { en: 'Replace the room screen link?' },
  'admin.theCurrentRoomScreen': { en: 'The current room screen link and PowerPoint slide link stop working, including on screens and slides already showing them. Copy the new links into those places. Participants are not affected.' },
  'admin.replaceLink': { en: 'Replace link' },
  'admin.newRoomScreenAnd': { en: 'New room screen and slide links created' },
  'admin.panelistView2': { en: 'Panelist view' },
  'admin.qaFacilitatorQueue': { en: 'QA Facilitator queue' },
  'admin.participantLink': { en: 'Participant link' },
  'admin.replaceParticipantLink': { en: 'Replace participant link' },
  'admin.replaceTheParticipantLink': { en: 'Replace the participant link?' },
  'admin.theOldLinkStops': { en: 'The old link stops working for anyone who has not joined yet. People already in the session can keep asking.' },
  'admin.newParticipantLinkCreated': { en: 'New participant link created' },
  'admin.inRoomSessionsHave': { en: 'In-room sessions have no participant link — people join by scanning the room screen.' },
  'admin.ifALinkShows': { en: 'If a link shows Google\'s "Sorry, unable to open the file at this time", the browser is signed into more than one Google account. Open the link in a private browsing window. Use one on the projector computer too.' },
  'admin.editSession': { en: 'Edit session' },
  'admin.newSession': { en: 'New session' },
  'admin.noQaFacilitatorsYet': { en: 'No QA Facilitators yet.' },
  'admin.sessionLogo': { en: 'Session logo' },
  'admin.usesTheOrganizationLogo': { en: 'Uses the organization logo' },
  'admin.sessionLogoSaved': { en: 'Session logo saved' },
  'admin.sessionLogoRemoved': { en: 'Session logo removed' },
  'admin.newEvent': { en: 'New event' },
  'admin.noQaFacilitatorsYet2': { en: 'No QA Facilitators yet. Add them on the People tab.' },
  'admin.noEventCoordinatorsYet': { en: 'No Event Coordinators yet. Add them on the People tab.' },
  'admin.eventLogo': { en: 'Event logo' },
  'admin.usesTheSiteLogo': { en: 'Uses the site logo' },
  'admin.eventLogoSaved': { en: 'Event logo saved' },
  'admin.eventLogoRemoved': { en: 'Event logo removed' },
  'admin.checking': { en: 'Checking…' },
  'admin.wholeApp': { en: 'Whole app' },
  'admin.thisEventHasNo': { en: 'This event has no sessions yet.' },
  'admin.chooseACsvFile': { en: 'Choose a CSV file or paste one first.' },
  'admin.eventSaved': { en: 'Event saved' },
  'admin.eventCreatedAddIts': { en: 'Event created — add its sessions' },
  'admin.sessionSaved': { en: 'Session saved' },
  'admin.sessionCreatedActivateIt': { en: 'Session created — activate it when you are ready' },
  'admin.anyoneWithThisLink': { en: 'Anyone with this link can ask a question.' },
  'admin.notAvailableInRoom': { en: 'Not available: in-room sessions are joined by scanning the room screen.' },
  'admin.googleDoesNotTell': { en: 'Google does not tell the app who is signed in from any other domain.' },
  'admin.createsOneAndSends': { en: 'creates one and sends them a set-your-password email.' },
  'admin.noneYet': { en: 'None yet' },
  'admin.languagesSaved': { en: 'Languages saved' },
  'admin.currentLogo': { en: 'Current logo' },
  'admin.noLogo': { en: 'No logo' },
  'admin.aKeyIsSaved': { en: 'A key is saved. Paste a new one to replace it; the key itself is never shown again.' },
  'admin.noKeyYetWithout': { en: 'No key yet. Without one, questions still arrive and can be answered — they are simply not grouped or translated.' },
  'admin.pasteAKeyFirst': { en: 'Paste a key first.' },
  'admin.geminiKeySaved': { en: 'Gemini key saved' },
  'admin.removeTheGeminiKey': { en: 'Remove the Gemini key?' },
  'admin.questionsWillStillArrive': { en: 'Questions will still arrive and can be answered, but nothing will be grouped or translated until a key is added again.' },
  'admin.geminiKeyRemoved': { en: 'Gemini key removed' },
  'admin.editedHere': { en: 'Edited here' },
  'admin.theBuiltInPrompt': { en: 'The built-in prompt' },
  'admin.promptSavedUsedFrom': { en: 'Prompt saved — used from the next request' },
  'admin.putTheBuiltIn': { en: 'Put the built-in prompt back?' },
  'admin.builtInPromptRestored': { en: 'Built-in prompt restored' },
  'admin.modelDefault': { en: 'Model default' },
  'admin.minimalFastest': { en: 'Minimal (fastest)' },
  'admin.highSlowest': { en: 'High (slowest)' },
  'admin.geminiSettingsSavedUsed': { en: 'Gemini settings saved — used from the next request' },
  'admin.geminiSettingsReset': { en: 'Gemini settings reset' },
  'admin.loadTestReadyRun': { en: 'Load test ready — run the command' },
  'admin.finishTheLoadTest': { en: 'Finish the load test?' },
  'admin.theTestEndpointIs': { en: 'The test endpoint is switched off, and its session and every test question are deleted.' },
  'admin.finishAndDelete': { en: 'Finish and delete' },
  'admin.loadTestFinishedAnd': { en: 'Load test finished and cleaned up' },
  'admin.removeSummaryRecipient': { en: 'Remove summary recipient?' },
  'admin.brandingSaved': { en: 'Branding saved' },
  'admin.logoSaved': { en: 'Logo saved' },
  'admin.removeTheLogo': { en: 'Remove the logo?' },
  'admin.pagesWillShowYour': { en: 'Pages will show your organization name instead.' },
  'admin.removeLogo': { en: 'Remove logo' },
  'admin.logoRemoved': { en: 'Logo removed' },
  'admin.couldNotReadThat': { en: 'Could not read that file.' },
  'admin.thatFileIsNot': { en: 'That file is not an image this browser can read.' },
  'admin.thatImageIsToo': { en: 'That image is too detailed to use as a logo. Try a simpler or smaller version.' },

  'admin.copied': { en: 'Copied' },
  'admin.details': { en: 'Details' },
  'admin.action': { en: 'Action' },
  'admin.who': { en: 'Who' },
  'admin.when': { en: 'When' },
  'admin.send': { en: 'Send' },
  'admin.restore': { en: 'Restore' },
  'admin.links': { en: 'Links' },
  'admin.duplicate': { en: 'Duplicate' },
  'admin.edit': { en: 'Edit' },
  'admin.archive': { en: 'Archive' },
  'admin.delete': { en: 'Delete' },
  'admin.copy': { en: 'Copy' },
  'admin.open': { en: 'Open' },
  'admin.notes': { en: 'Notes' },
  'admin.result': { en: 'Result' },
  'admin.session': { en: 'Session' },
  'admin.event': { en: 'Event' },
  'admin.row': { en: 'Row' },
  'admin.problem': { en: 'Problem' },
  'admin.skip': { en: 'Skip' },
  'admin.update': { en: 'Update' },
  'admin.updated': { en: 'Updated' },
  'admin.create': { en: 'Create' },
  'admin.created': { en: 'Created' },
  'admin.you': { en: 'You' },
  'admin.owner': { en: 'Owner' },
  'admin.remove': { en: 'Remove' },
  'admin.saved': { en: 'Saved' },
  'admin.reset': { en: 'Reset' },
  'admin.medium': { en: 'Medium' },
  'admin.low': { en: 'Low' },

  'admin.eventOption': { en: 'Event: {name}' },
  'admin.signedInAs': { en: 'Signed in as {email}' },
  'admin.version': { en: 'Version {version}' },
  'admin.activityShowing': { en: 'Showing the {shown} most recent{scanned}.' },
  'admin.activityOfLast': { en: ' of the last {n} entries' },
  'admin.waitMinutes': { en: '{m} min between questions' },
  'admin.waitSeconds': { en: '{s} s between questions' },
  'admin.waitMinutesSeconds': { en: '{m} min {s} s between questions' },
  'admin.evSessions.one': { en: '{n} session' },
  'admin.evSessions.other': { en: '{n} sessions' },
  'admin.evActive': { en: '{n} active' },
  'admin.evCoordinators.one': { en: '{n} Event Coordinator' },
  'admin.evCoordinators.other': { en: '{n} Event Coordinators' },
  'admin.brandedAs': { en: 'branded as {name}' },
  'admin.mailFacilitatorsBody.one': { en: '{n} QA Facilitator gets one email with the queue link for each session they are running in {event} ({open}): {people}.' },
  'admin.mailFacilitatorsBody.other': { en: '{n} QA Facilitators each get one email with the queue link for each session they are running in {event} ({open}): {people}.' },
  'admin.openSessions.one': { en: '{n} session that hasn\'t ended' },
  'admin.openSessions.other': { en: '{n} sessions that haven\'t ended' },
  'admin.sentFacilitators': { en: 'Sent {emails} covering {sessions}' },
  'admin.sentEmails.one': { en: '{n} email' },
  'admin.sentEmails.other': { en: '{n} emails' },
  'admin.copiedEventWith': { en: 'Copied {name} with its {sessions}' },
  'admin.deleteEventBody.one': { en: 'Its {n} session is kept and moves to "Not in an event", with the site branding. Event branding and logo are deleted.' },
  'admin.deleteEventBody.other': { en: 'Its {n} sessions are kept and move to "Not in an event", with the site branding. Event branding and logo are deleted.' },
  'admin.archivedSessions': { en: 'Archived sessions · {n}' },
  'admin.archivedHint': { en: 'Ended sessions move here {days} days after ending, to keep the app fast. Their questions stay in the spreadsheet. Restore one to email its summary again.' },
  'admin.archivedEnded': { en: ' · ended {at}' },
  'admin.restored': { en: 'Restored {name}' },
  'admin.metaQuestions.one': { en: '{n} question' },
  'admin.metaQuestions.other': { en: '{n} questions' },
  'admin.metaPrepared': { en: ' (+{n} prepared)' },
  'admin.metaFacilitators.one': { en: '{n} QA Facilitator' },
  'admin.metaFacilitators.other': { en: '{n} QA Facilitators' },
  'admin.metaMaxChars': { en: 'max {n} chars' },
  'admin.metaEnded': { en: 'ended {at}' },
  'admin.metaStarted': { en: 'started {at}' },
  'admin.metaCreated': { en: 'created {at}' },
  'admin.metaBrandedFor': { en: 'branded for {name}' },
  'admin.metaSummaryPending': { en: 'summary email not sent yet ({why}) — retrying every 30 minutes, or use Email summary' },
  'admin.metaSummarySent': { en: 'summary emailed {at}' },
  'admin.sentLinksTo.one': { en: 'Sent room screen and queue links to {n} QA Facilitator' },
  'admin.sentLinksTo.other': { en: 'Sent room screen and queue links to {n} QA Facilitators' },
  'admin.sessionEnded': { en: 'Session ended{emailed}{note}' },
  'admin.sessionEndedEmailed': { en: ' — summary emailed to {to}' },
  'admin.archived': { en: 'Archived {name}' },
  'admin.deleteSessionBody.one': { en: 'This permanently deletes the session and all {n} question, topics and votes. It cannot be undone.' },
  'admin.deleteSessionBody.other': { en: 'This permanently deletes the session and all {n} questions, topics and votes. It cannot be undone.' },

  'admin.endSessionBody': { en: 'Participants can no longer ask questions, and an ended session cannot be reopened.{summary}' },
  'admin.endSessionSummaryTo': { en: '\n\nThe questions summary will be emailed to {to}.' },
  'admin.cooldownHint': { en: '0 for no wait, up to {max} (one hour). Changes apply immediately, even to phones already waiting.' },
  'admin.maxHint': { en: 'Between 50 and {max}. Shorter questions are easier to read aloud.' },
  'admin.guestUrlHint': { en: 'Uses {url}' },
  'admin.checklistTitle': { en: 'Day-of checklist — {event}' },
  'admin.checklistWhen': { en: '{problems}{warnings} · checked {at}. ✓ ready · ! worth a look · ✗ needs fixing.' },
  'admin.checklistProblems.one': { en: '{n} problem' },
  'admin.checklistProblems.other': { en: '{n} problems' },
  'admin.checklistNoProblems': { en: 'No problems' },
  'admin.checklistWarnings': { en: ', {n} to look at' },
  'admin.exportHint.one': { en: '{n} session exported as {file}. If the download didn\'t start, copy the text below into a file ending in .csv.' },
  'admin.exportHint.other': { en: '{n} sessions exported as {file}. If the download didn\'t start, copy the text below into a file ending in .csv.' },
  'admin.imported': { en: 'Imported: {created} created, {updated} updated, {skipped} skipped, {failed} with problems (not imported).' },
  'admin.checked': { en: 'Check: {created} to create, {updated} to update, {skipped} to skip, {failed} with problems.{events}' },
  'admin.checkedNewEvents': { en: ' New events: {names}.' },
  'admin.importGo.one': { en: 'Import {n} session' },
  'admin.importGo.other': { en: 'Import {n} sessions' },
  'admin.importDone': { en: 'Imported {n} sessions{problems}' },
  'admin.importProblems': { en: ' — {n} rows had problems' },
  'admin.sentEventSummary.one': { en: 'Event summary sent to {n} person' },
  'admin.sentEventSummary.other': { en: 'Event summary sent to {n} people' },
  'admin.sentSummary.one': { en: 'Summary sent to {n} person' },
  'admin.sentSummary.other': { en: 'Summary sent to {n} people' },
  'admin.sentLinks.one': { en: 'Links sent to {n} person' },
  'admin.sentLinks.other': { en: 'Links sent to {n} people' },
  'admin.domainHint': { en: 'Only @{domain} accounts can be administrators, QA Facilitators or Event Coordinators. ' },
  'admin.removePersonTitle': { en: 'Remove {role}?' },
  'admin.roleAdministrator': { en: 'administrator' },
  'admin.roleCoordinator': { en: 'Event Coordinator' },
  'admin.roleFacilitator': { en: 'QA Facilitator' },
  'admin.removeFacilitatorBody': { en: '{email} will also be removed from every session.' },
  'admin.removeCoordinatorBody': { en: '{email} will also be removed from every event, and can no longer open a coordinator portal.' },
  'admin.removeAdminBody': { en: '{email} will no longer be able to open the Admin page.' },
  'admin.removed': { en: 'Removed {email}' },
  'admin.added': { en: 'Added {email}' },
  'admin.storageUsed': { en: '{pct}% of the 500 KB Google allows for settings (sessions, events, people). Ended sessions are archived after 30 days to keep it low.' },
  'admin.retentionBody': { en: 'Within the hour, the wording of every question from sessions that ended more than {months} months ago is removed for good. Topics, counts and answered status stay.' },
  'admin.sentTo': { en: 'Sent to {email}' },
  'admin.groupingFailing': { en: '{n} failed runs in a row — {why}' },
  'admin.groupingWorking': { en: 'Working (last {at})' },
  'admin.promptEdited': { en: '{label} — edited' },
  'admin.promptNeeds': { en: 'Must still contain {tokens}. Question Desk fills those in before sending.' },
  'admin.promptNeedsJoin': { en: ' and ' },
  'admin.promptResetBody': { en: 'Your wording for “{label}” is replaced by the one Question Desk ships with.' },
  'admin.thinkingRecommended': { en: '{label} — recommended' },
  'admin.geminiResetBody': { en: 'Back to {model}, the recommended thinking levels, temperature {temperature} and {batchSize} questions per grouping request.' },
  'admin.tryTask': { en: '{task} · thinking {thinking}' },
  'admin.trySeconds': { en: '{seconds} seconds{retried}' },
  'admin.tryRetried': { en: ' — this model doesn’t accept that thinking level, so it ran without it' },
  'admin.modelsListed': { en: ' {n} models — click the Model box to pick one.' },
  'admin.checksNeedAttention': { en: '{n} check(s) need attention' },
  'admin.removeRecipientBody': { en: '{email} will no longer get session summaries.' },

  'admin.nothingGroupedYet': { en: 'Nothing grouped yet' },
  'admin.resetGeminiSettings': { en: 'Reset Gemini settings?' },
  'admin.allChecksPassed': { en: 'All checks passed' },
  'admin.removeOldQuestionWording': { en: 'Remove old question wording?' },
  'admin.removeOldWording': { en: 'Remove old wording' },

  'admin.everyoneSignsIn': { en: 'Everyone here signs in with an account on this site. Adding an address that has no account ' },
  'admin.askingGemini': { en: 'Asking Gemini with these settings…' },
  'admin.triedModel': { en: 'Tried {model} — nothing saved yet' },
  'admin.loadingModels': { en: ' Loading…' },
  'admin.healthChecking': { en: 'Checking…' },
  'admin.healthCouldNotRun': { en: 'The health check could not run. Try again.' },

  'admin.personLanguage': { en: 'Language {email} reads the app in' },
  'admin.languageSet': { en: '{email} now reads the app in {language}' },
  'admin.roomLanguageLabel': { en: 'Room language' },
  'admin.roomLanguageHint': { en: 'The room screen, slide and panelist view read their status lines in this. Blank uses the site\'s.' },
  'admin.useSiteLanguage': { en: 'Use the site\'s' },
  'admin.appLanguageLabel': { en: 'App language' },
  'admin.appLanguageHint': { en: 'What staff read when they have not chosen for themselves, and what every room screen reads.' },
  'admin.appLanguageSaved': { en: 'App language saved' },

  'mod.eventTeam': { en: 'Event team' },
  'mod.eventTeamDone': { en: 'Event team ✓' },
  'mod.alsoShownAnswerNow': { en: 'With Answer now, phones and the room screen show' },
  'mod.readOutFor': { en: 'Question to read out for {topic}' },
  'mod.mergeBusy': { en: 'Gemini is writing one question for this topic. This can take up to half a minute.' },
  'mod.rewriteWithGemini': { en: 'Rewrite with Gemini' },
  'mod.writeReadOut': { en: 'Write one question to read out' },
  'mod.mergeHint.one': { en: 'Gemini combines this {n} question into one. You can edit it.' },
  'mod.mergeHint.other': { en: 'Gemini combines these {n} questions into one. You can edit it.' },
  'mod.trTopicOnPhones': { en: 'Topic on phones' },
  'mod.trTopicIfShown': { en: 'Topic, if shown on phones' },
  'mod.trReadOut': { en: 'Read-out question' },
  'mod.moreActions': { en: 'More actions for {topic}' },
  'mod.groupingLate': { en: 'Grouping runs every minute. Questions still waiting? Press Group now, or run the health check on the Admin page.' },
  'mod.selectQuestion': { en: 'Select this question' },

  'panel.nowAnswering': { en: 'Now answering' },
  'panel.timerTitle': { en: 'Time on this question' },
  'panel.waiting': { en: 'Waiting for the facilitator to choose a question.' },
  'panel.ended': { en: 'This session has ended. Thank you.' },
  'panel.notStarted': { en: 'This session hasn\'t started yet.' },
  'panel.live': { en: 'Updates automatically' },
  'panel.stale': { en: 'Not updating — check the connection' },

  'present.waitingToStart': { en: 'Waiting for this session to start' },
  'present.codeRefreshes': { en: 'Code refreshes automatically' },
  'present.paused': { en: 'Questions are paused' },
  'present.lostConnection': { en: 'Lost connection — retrying' },
  'present.stale': { en: 'Not updating — check the internet connection. This code may have expired.' },
  'present.codeUpdated': { en: ' · code updated {at}' },

  'sheet.pageTitle': { en: '{event} — QR sheets' },
  'sheet.print': { en: 'Print' },
  'sheet.download': { en: 'Download QR images' },
  'sheet.downloadFallback': { en: 'Save each image below' },
  'sheet.intro.one': { en: '{n} page for {event}, one per shareable-link session. Print on letter or A4.' },
  'sheet.intro.other': { en: '{n} pages for {event}, one per shareable-link session. Print on letter or A4.' },
  'sheet.nothing': { en: 'No sessions in {event} use a shareable link, so there is nothing to print.' },
  'sheet.qr': { en: 'QR code' },
  'sheet.qrFor': { en: 'QR code for {name}' },
  'sheet.skipped': { en: 'Not printed (in-room sessions join by the changing code on the room screen): {names}.' },
  'sheet.saveByHand': { en: 'Right-click (or press and hold) each image to save it.' },

  'coord.title': { en: 'Event logistics' },
  'coord.pageTitle': { en: '{event} — event logistics' },
  'coord.loading': { en: 'Loading…' },
  'coord.adminLink': { en: 'Admin' },
  'coord.waiting': { en: '{n} waiting' },
  'coord.allSorted': { en: 'All sorted' },
  'coord.tally.one': { en: '{n} question about running the event' },
  'coord.tally.other': { en: '{n} questions about running the event' },
  'coord.lead': { en: 'Questions the audience asked about the event itself — rooms, timing, access, food, signage. They are also in each session’s queue, so a facilitator can answer from the stage; tick one here when it has been dealt with.' },
  'coord.answered': { en: 'Answered in the session' },
  'coord.putBack': { en: 'Put back' },
  'coord.sorted': { en: 'Sorted' },
  'coord.empty': { en: 'Nothing yet. Questions about rooms, timing, access or anything else about running the event will appear here as they are asked.' }
};

/** Pages that read BOOT.words. Ask.html is not one: participants get BOOT.text instead. */
const APP_TEXT_FOR = {
  'Admin.html': true,
  'Coordinator.html': true,
  'Home.html': true,
  'Moderate.html': true,
  'Panel.html': true,
  'Present.html': true,
  'Sheet.html': true
};

/** Fills {name} placeholders. Anything the catalog has no value for is left as it stands. */
function format_(text, vars) {
  if (!vars) return text;
  return String(text).replace(/\{(\w+)\}/g, function (whole, name) {
    return vars[name] === undefined || vars[name] === null ? whole : String(vars[name]);
  });
}

/**
 * Which plural form a count takes. English and Spanish agree (one / other); a language that
 * needs more forms adds itself here rather than to 27 call sites.
 */
function plural_(lang, n) {
  return Number(n) === 1 ? 'one' : 'other';
}

/** An app language code we actually have, or English. */
function appLanguageCode_(code) {
  return code && CONFIG.appLanguages[code] ? code : 'en';
}

/** The whole catalog in one language, English wherever that language has no wording yet. */
function wordsFor_(lang) {
  const code = appLanguageCode_(lang);
  const out = {};
  Object.keys(APP_TEXT).forEach(function (key) {
    out[key] = APP_TEXT[key][code] || APP_TEXT[key].en;
  });
  return out;
}

/** One phrase, for the server's own use (errors, emails). */
function t_(key, vars, lang) {
  const entry = APP_TEXT[key];
  if (!entry) throw new Error('Unknown phrase ' + key + '.');
  return format_(entry[appLanguageCode_(lang)] || entry.en, vars);
}

/** An app language a form offered, or '' for "use the default". */
function cleanAppLanguage_(code) {
  const clean = String(code || '');
  if (clean && !CONFIG.appLanguages[clean]) throw new Error(t_('err.notAnAppLanguage', { code: clean }));
  return clean;
}

/** t_() for a count: the catalog holds key.one and key.other, as Wn() reads them on a page. */
function tn_(key, n, vars, lang) {
  const all = {};
  if (vars) Object.keys(vars).forEach(function (name) { all[name] = vars[name]; });
  if (all.n === undefined) all.n = n;
  return t_(key + '.' + plural_(lang, n), all, lang);
}

/** The language one person reads the app in. Set per person on the People tab. */
function appLanguage_(email) {
  if (email === undefined) email = currentEmail_();
  const saved = personLanguages_()[String(email || '').toLowerCase()];
  return appLanguageCode_(saved || siteLanguage_());
}

/** Everyone's chosen language, by address. */
function personLanguages_() {
  try {
    return JSON.parse(props_().getProperty('PEOPLE_LANG') || '{}') || {};
  } catch (err) {
    return {};
  }
}

/** The site's own language: what a room screen and anyone with no choice of their own reads. */
function siteLanguage_() {
  return appLanguageCode_(props_().getProperty('APP_LANGUAGE'));
}

/**
 * The language a room screen, slide and panelist view speak. Nobody is signed in at a venue
 * laptop, so it follows the session, then its event, then the site.
 */
function roomLanguage_(session) {
  if (session && session.roomLanguage) return appLanguageCode_(session.roomLanguage);
  const ev = session && session.eventId ? getEvent_(session.eventId) : null;
  if (ev && ev.roomLanguage) return appLanguageCode_(ev.roomLanguage);
  return siteLanguage_();
}
